### ISSUE TITLE
Unrealistically large aerosol mixing ratios

### ISSUE THREAD

**Issue by rmontuoro** [ufs-community/ufs-weather-model#713] opened 2021-07-26 18:13 UTC
## Description
Aerosol mixing ratios grow exponentially and become unrealistically large over a 24-hour forecast run with prognostic aerosols if using revision 766f511 (PR #592) or later. This becomes evident after cold-start and cycled experiments (where aerosol mixing ratios are initialized with non-zero values) at C96 resolution.

Development and verification efforts involving prognostic aerosols should be carried out using prior code revisions (not earlier than a842d57) until this issue has been addressed. A hotfix is being developed.

### To Reproduce:
Run a cycled case using the `feature/aerosols` branch of the [global-workflow](https://github.com/rmontuoro/global-workflow.git) and model revision 766f511, following the instructions in the README file.

## Output

**output logs for coupled UFS-Aerosol runs**
- **Test 1: Coupled FV3-GOCART run (baseline)**
Code revision: a842d57 (July 1, PR #591)
CCPP physics suite: FV3_GFS_v16
Summary tracer output:
```
  0:  so2  9.539526097204887E-002  0.000000000000000E+000  3.087992863100456E-004
  0:  so4   28.4377589696771       0.000000000000000E+000  0.243503072990529     
  0:  dms  2.610503840815381E-003  0.000000000000000E+000  8.286564200966070E-005
  0:  msa  1.296207311818483E-004  0.000000000000000E+000  2.646171557951862E-006
  0:  bc1   25.7945680463166       9.812665485667373E-024  2.688528105173283E-002
  0:  bc2   7.50250676487166       0.000000000000000E+000  1.249664010365909E-002
  0:  oc1   367.503994872770       9.819704464923638E-024  0.123538034063876     
  0:  oc2   394.058963010346       0.000000000000000E+000  0.337448669733756     
  0:  dust1   2470.85510441649       0.000000000000000E+000   8.77264307474775     
  0:  dust2   2780.05333524100       0.000000000000000E+000   10.7798772103039     
  0:  dust3   2943.77235646700       0.000000000000000E+000   11.8408856075976     
  0:  dust4   2551.30672530626       0.000000000000000E+000   8.62093678592545     
  0:  dust5   1776.79048182558       0.000000000000000E+000   4.55699920418956     
  0:  seas1  0.159322304328674       0.000000000000000E+000  4.766661843526808E-003
  0:  seas2   5.13339552824921       0.000000000000000E+000  0.155582747783381     
  0:  seas3   44.6260677952227       0.000000000000000E+000   1.59706002693491     
  0:  seas4   118.973407869642       0.000000000000000E+000   5.58375844683846     
  0:  seas5   40.7275353815133       0.000000000000000E+000   1.73753938043137     
  0:  nh3   101.062858209331       0.000000000000000E+000  0.302197046188163     
  0:  nh4a   13.7559366288646       0.000000000000000E+000  7.112446564985191E-002
  0:  no3an1   3.10483438851343       0.000000000000000E+000  8.465371905053884E-003
  0:  no3an2   2.74551802045499       0.000000000000000E+000  2.242286188522219E-002
  0:  no3an3  9.618509550684523E-002  0.000000000000000E+000  4.177910296939359E-004
  0:  pm25   3876.32098544758       1.009664660284811E-026   16.9327957405695     
  0:  pm10   11074.9582863870       1.009664660284811E-026   51.3619291427217     
```

- **Test 2: Coupled UFS-Aerosols run with update**
Code revision: 766f511 (July 16, PR #592)
CCPP physics suite: FV3_GFS_v16
Model configuration: no shallow convective transport for aerosols
Summary tracer output:
```
  0:  so2   14670291.0701031       0.000000000000000E+000   20.0425514485201     
  0:  so4   11508399766.3621       0.000000000000000E+000   12523.1732231806     
  0:  dms  0.507918813155905       0.000000000000000E+000  9.949144012552224E-005
  0:  msa  6.629165262572248E-002  0.000000000000000E+000  8.236385323020113E-006
  0:  bc1   313914461.950873       9.817351002115697E-024   494.020776942678     
  0:  bc2   276068108.172452       0.000000000000000E+000   456.756409883897     
  0:  oc1   855930792.416290       9.840210376903559E-024   1485.08878517209     
  0:  oc2   25757078809.1677       0.000000000000000E+000   46715.3421968033     
  0:  dust1   168690032380346.       0.000000000000000E+000   254389829.526212     
  0:  dust2   204680274911206.       0.000000000000000E+000   308814131.726501     
  0:  dust3   223202809900706.       0.000000000000000E+000   336801989.507946     
  0:  dust4   102509957659133.       0.000000000000000E+000   156558886.858154     
  0:  dust5   15867217357420.9       0.000000000000000E+000   25223235.7256107     
  0:  seas1   32.7227214100948       0.000000000000000E+000  9.405392220586870E-003
  0:  seas2   1064.45035947009       0.000000000000000E+000  0.307138301055097     
  0:  seas3   10437.3298668171       0.000000000000000E+000   3.16822051182702     
  0:  seas4   24844.5415414950       0.000000000000000E+000   11.0234941936819     
  0:  seas5   235.513023669972       0.000000000000000E+000   2.13478589401377     
  0:  nh3   255263721700.976       0.000000000000000E+000   352309.851016600     
  0:  nh4a   4349701777.52637       0.000000000000000E+000   5093.89872089953     
  0:  no3an1   1136396155.71800       0.000000000000000E+000   1710.04119832862     
  0:  no3an2   46327359036.1886       0.000000000000000E+000   68763.0049866038     
  0:  no3an3   2071246487.01287       0.000000000000000E+000   3200.82433477488     
  0:  pm25   217656179821200.       1.009496698824618E-026   416944465.857888     
  0:  pm10   593721601189342.       1.009496698824618E-026   1139182261.90573    
```

**Comment by junwang-noaa** [comment] 2021-08-17 18:11
The issue is fixed in PR#725, close issue.

**Closed as completed by junwang-noaa** 2021-08-17 18:11 UTC
Labels: bug
