### ISSUE TITLE
Broken AQM submodule

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#1934] opened 2023-10-05 16:46 UTC
## Description
It seems that AQM submodule is broken. It indicates that `UTIL/create_ebi/src_RXNSU/junit.F` and `UTIL/inline_phot_preproc/src/CSQY_DATA.F` are modified after fresh clone.

### To Reproduce:
What compilers/machines are you seeing this with? Orion
Give explicit steps to reproduce the behavior.
1. git clone --recursive https://github.com/ufs-community/ufs-weather-model.git
2. cd ufs-weather-model
3. git status

## Additional context
N/A

## Output
```
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   AQM (modified content)

no changes added to commit (use "git add" and/or "git commit -a")
```

```
$ ufs-weather-model/AQM/src/model/CMAQ [(HEAD detached at be5d28fd1)] $ git status       
HEAD detached at be5d28fd1
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   UTIL/create_ebi/src_RXNSU/junit.F
	modified:   UTIL/inline_phot_preproc/src/CSQY_DATA.F
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by DeniseWorthen** [comment] 2023-10-05 17:05
@uturuncoglu I just cloned ufs-weather-model on orion and didn't see the issue. I used

git clone https://github.com/ufs-community/ufs-weather-model.git
cd ufs-weather-model/
git submodule update --init --recursive

**Comment by uturuncoglu** [comment] 2023-10-05 17:08
@DeniseWorthen Strange. I also cloned couple of minutes ago. Could you try with `git clone --recursive https://github.com/ufs-community/ufs-weather-model.git` again. You are doing in two steps. Maybe it makes the difference. Let me double check in my side too.

**Comment by uturuncoglu** [comment] 2023-10-05 17:13
@DeniseWorthen Okay. On Orion it seems fine and I could not reproduce the issue. Maybe it is because of git version. On my local Mac I have still issue. On Orion the git version is `git version 1.8.3.1` and on my local machine it is `git version 2.37.1 (Apple Git-137.1)`.

**Comment by uturuncoglu** [comment] 2023-10-05 17:16
On Orion, I also test with loading the git module with `module load git` and it loads `git version 2.28.0`. I clone the model with this version and it seems there is no any issue. Maybe it is specific to my local Mac or could be still issue in that submodule. Not sure.

**Comment by DeniseWorthen** [comment] 2023-10-05 17:19
I can checkout on my mac (git version 2.39.3 (Apple Git-145)).

**Comment by uturuncoglu** [comment] 2023-10-05 17:21
@DeniseWorthen I have out of idea. Maybe it is specific to my machine but having issue with only those two files seems strange.

**Comment by DeniseWorthen** [comment] 2023-10-10 20:04
@uturuncoglu Can we close this?

**Comment by MicroTed** [comment] 2023-10-11 23:02
I found this issue because I was also seeing this on Macos (ventura) while trying to update a PR. I used

git clone --branch develop --recursive https://github.com/ufs-community/ufs-weather-model.git

git version 2.39.2 (Apple Git-143)

And the same result with git from homebrew (git version 2.42.0).

**Comment by uturuncoglu** [comment] 2023-10-12 04:43
@MicroTed Thanks. It seems that this is reproducible at least one other user. @DeniseWorthen I am not sure but it seems there could be issue with the component and its commits. Anyway, if you think that there is no any issue, please close it. Thanks again helping me about it.

**Comment by MicroTed** [comment] 2023-10-12 14:35
I think the problem is having git ignoring case on the Mac, since the difference is the filenames:
junit.F (hera) vs. junit.f (mac)
CSQY_DATA.F (hera) vs. CSQY_DATA.f (mac)

Although I have my global .gitconfig setting as
[core]
        ignorecase = false

But in the cloned directory, .git/config has ignorecase = true

I'm not a git wizard, but this seems odd?

P.S.: and the junit.f in the mac clone is set as executible:
-rwxr-xr-x  1 ted.mansell  staff   3.5K Oct 11 17:35 AQM/src/model/CMAQ/UTIL/create_ebi/src_RXNSU/junit.f*

P.P.S: If I set the local git config to 'ignorecase = false' and then mv the AQM directory and do a submodule update, it *still* gives a junit.f and says there are local modifications. Is that an old version of the file that is somehow stuck there because of a name change from .f to .F?

**Comment by uturuncoglu** [comment] 2023-10-12 14:39
@MicroTed Yes, it is strange. BTW, I had this issue on Orion too. So, maybe it is not specific to Mac and also @DeniseWorthen is able to checkout without any issue.

**Comment by MicroTed** [comment] 2023-10-12 15:43
I created a disk image with a case-sensitive APFS, and now the git clone shows clean. So it would seem to be a file system  issue, but I would think that Orion has a case sensitive FS? Mac is case preserving, though, so unless there is both a junit.f and a junit.F in the same directory, I don't know why it would matter.

**Comment by uturuncoglu** [comment] 2023-10-12 15:47
@MicroTed Thanks for extra testing. I am not sure about Orion but it is highly possible it is case sensitive. I wonder if they changed those file extensions recently or not? @rmontuoro Do you have any idea?

**Comment by MicroTed** [comment] 2023-10-16 21:17
Oh, duh, there  *are* both junit.F and junit.f in the directory.  There is a PR about this, too, from May 2022: https://github.com/USEPA/CMAQ/pull/171 The PR removes junit.f (and changes the makefile to use junit.F), and also removes both of the CSQY_DATA files and a couple other files.

**Comment by BrianCurtis-NOAA** [comment] 2024-01-30 13:29
Yes, I do recall this issue. There is work by the AQM devs to bring CMAQ to 5.4 for the next development iteration of the AQM component. I don't forsee this getting fixed until that version bump comes into AQM. I'll leave this issue here so we can close it at that point.

**Comment by junwang-noaa** [comment] 2024-04-12 14:43
@uturuncoglu With @BrianCurtis-NOAA's comments, we will close the issue then.

**Closed as completed by junwang-noaa** 2024-04-12 14:43 UTC
Labels: bug
