### ISSUE TITLE
LBC issue with the UFS-AQM prediction of PM2.5

### ISSUE THREAD

**Issue by JianpingHuang-NOAA** [ufs-community/ufs-weather-model#1404] opened 2022-09-07 18:53 UTC
## Description
 I am testing the UFS-AQM model for the large domain which covers CONUS, AK and HI (slide 2) with grid-spacing of 13 km and 64 vertical levels.  The simulation started  from 20220901 at 12z with the clean atmospheric chemistry condition. After 6-hr simulation, PM2.5 started to increase from south border (slide 3). 12-hr later, high PM2.5 is clearly seen near south border.  Meanwhile, some high PM2.5 spots started to appear near west and east borders (slide 4).  High PM2.5 concentration can be found clearly near south, east, and west borders at the 24-hr simulation.  Those PM2.5 concentrations are highly related to sea salt and chlorine species in coarse mode.  This indicates that PM2.5 comes from sea slat emissions driven by wind speeds near borders.  In other words, something must be wrong with lateral boundary conditions of wind speeds. 

Does anyone have any suggestion on this?

The sides can be found from the link below
(https://docs.google.com/presentation/d/1cWwPYKl_4rKJzV8oQmg_D1hmrEICM4K4/edit#slide=id.g15126239a7a_0_5)

Thanks.

Jianping

**Comment by ytangnoaa** [comment] 2022-09-09 17:10
Jianping

Could you identify which aerosol species cause these high values? You mentioned the wind-driven sea salt. Does the 10-m wind over those spots become unusually higher?

Thanks

Youhua

**Comment by HaixiaLiu-NOAA** [comment] 2022-09-17 14:42
@JianpingHuang-NOAA could you please update this issue with your fix to the LBC issue and close it? Thank you.

**Comment by bbakernoaa** [comment] 2022-09-19 19:33
@JianpingHuang-NOAA you mentioned there was an update to this but I haven't seen a PR put forth or a branch mentioned.  Can something be created so that the entire group can move forward.

**Comment by JianpingHuang-NOAA** [comment] 2022-09-19 19:57
Hi Barry and others.

The LBC issue was caused by an error related to Climatology Aerosol LBCs. There is no change for the code. I will send the location  of the updated LBCs file to Chan-Hoo to be included in the workflow. I am working on the testing of chemical ICs generator. I want to send both to Chan-Hoo together in next few days.

Jianping

**Comment by HaixiaLiu-NOAA** [comment] 2022-09-19 20:26
@JianpingHuang-NOAA This is great. Thank you so much. Let's communicate through the github issue to keep everyone updated.

**Comment by bbakernoaa** [comment] 2022-09-23 17:06
@JianpingHuang-NOAA are we not using GEFS for aerosols LBCs?

**Comment by ytangnoaa** [comment] 2022-09-23 17:33
Barry

The final LBC combines the static and GEFS LBCs, and the GEFS LBC mainly
represents fire, sea salt and dust influences.

Thanks

Youhua

**Comment by junwang-noaa** [comment] 2023-01-26 15:18
@JianpingHuang-NOAA I assume the issue is fixed, if yes, please close the issue. Thanks

**Comment by JianpingHuang-NOAA** [comment] 2023-01-26 15:28
@Jun Wang - NOAA Federal ***@***.***>   Done.

**Closed as completed** 2023-01-26 15:27 UTC
Labels: bug
