### ISSUE TITLE
v16 coupled tests can fail when output type is the tiled grid

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#566] opened 2021-05-10 13:19 UTC
## Description

This issue was first noted on Gaea with the coupled V16 tests failing with a PIO error. 

### To Reproduce:

Run the cpld_bmarkfrac_v16 test on Gaea using tiled grid output.

## Additional context

The initial issue was detailed in Issue #509. It was shown that:

1) changing the number of write tasks allowed the test to run
2) changing the output grid from tiled to gaussian allowed the test to run.

The issue appears to be related to the version and/or integration of PIO within ESMF.

**Comment by arunchawla-NOAA** [comment] 2021-05-10 14:13
Is this still limited to Gaea or can occur in other systems as well ?

**Comment by DeniseWorthen** [comment] 2021-05-10 14:42
We have only seen this issue on Gaea at this point.

**Comment by junwang-noaa** [comment] 2022-03-05 00:34
@DeniseWorthen Do we still have issue on gaea?

**Comment by DeniseWorthen** [comment] 2022-03-05 11:19
@junwang-noaa We turned off tiled output for this test on all platforms so it is not known whether the issue has been resolved. I suspect it is still an issue since the underlying problem was most likely due to the version of PIO we are using. I believe updating PIO is an active issue w/ the ESMF developers. Perhaps @rsdunlapiv could give an update.

**Comment by rsdunlapiv** [comment] 2022-03-05 23:19
The 8.3 release of ESMF should have an updated PIO (to version 2.5.6).  We should re-test at that point to see if the issue is resolved.

**Comment by arunchawla-NOAA** [comment] 2022-03-10 00:23
moving to icebox till the 8.3 release of esmf is available for further testing

**Comment by junwang-noaa** [comment] 2022-05-09 14:43
@DeniseWorthen The ESMF 830bs9 is now used in the UFS WM, can you check if the issue is resolved? Thanks

**Comment by rsdunlapiv** [comment] 2022-05-09 16:06
@DeniseWorthen @junwang-noaa 830bs09 does not have the PIO update.  I suggest waiting until the ESMF 8.3.0 release to test this.  Alternatively, you can test now with [830bs14](https://github.com/esmf-org/esmf/commits/v8.3.0b14) if would like.

**Comment by DeniseWorthen** [comment] 2022-05-09 17:07
I can confirm that 830bs09 does not resolve the tiled grid output issue for the bmark_p8 test. I still get the errror
```
304: fv3.exe            0000000001A80475  esmfpio_spmd_util         295  pio_spmd_utils.F90.in
```

**Comment by DeniseWorthen** [comment] 2023-01-20 18:13
I've been able to run the ``cpld_bmark_p8`` test using commit e051e0eac from the develop branch on Gaea but switching to the cubed_sphere_grid output. I was able to run 3 consecutive times. I'm not sure what has changed, since we're still running 8.3.0b09 in UWM but I'm going to close the issue at this point.

**Closed as completed** 2023-01-20 18:29 UTC
Labels: bug
