### ISSUE TITLE
no permission to access input data on HERA

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1852] opened 2023-08-03 02:38 UTC
## Description

Apparently there is a change in the fixed file location today, all my jobs failed because of this.
On HEAR /scratch2/NAGAPE/epic
drwxrwsrw-  3 Jong.Kim                   epic 4096 Aug  2 11:34 UFS-WM_RT

++ cp '/scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/MOM6_FIX/100/*' ./INPUT
cp: cannot stat '/scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/input-data-20221101/MOM6_FIX/100/*': Permission denied

**Comment by DeniseWorthen** [comment] 2023-08-03 11:53
@jiandewang @jkbk2004 I can confirm I also get this error.

**Comment by jkbk2004** [comment] 2023-08-03 13:06
@jiandewang @DeniseWorthen Looks like permission issue across different project. role.epic might be better solution. Can you try to run again with DISKNM=/scratch1/NCEPDEV/nems/role.epic/RT at line 307 of rt.sh ? Once it works, I will apply hot fix.

**Comment by BrianCurtis-NOAA** [comment] 2023-08-03 13:13
> @jiandewang @DeniseWorthen Looks like permission issue across different project. role.epic might be better solution. Can you try to run again with DISKNM=/scratch1/NCEPDEV/nems/role.epic/RT at line 307 of rt.sh ? Once it works, I will apply hot fix.

@jkbk2004 I'd recommend reverting those changes back to what they were until the permanent location changes have time to be tested and reviewed through a PR.

**Comment by jkbk2004** [comment] 2023-08-03 13:23
> > @jiandewang @DeniseWorthen Looks like permission issue across different project. role.epic might be better solution. Can you try to run again with DISKNM=/scratch1/NCEPDEV/nems/role.epic/RT at line 307 of rt.sh ? Once it works, I will apply hot fix.
> 
> @jkbk2004 I'd recommend reverting those changes back to what they were until the permanent location changes have time to be tested and reviewed through a PR.

@BrianCurtis-NOAA Still need PR to revert. Instead of two PRs (revert and new location). If you confirm DISKNM=/scratch1/NCEPDEV/nems/role.epic/RT, we can fix with single hot fix.

**Comment by BrianCurtis-NOAA** [comment] 2023-08-03 13:37
@jkbk2004 There are applicable shortcuts to the process where you can make a "hotfix". It's extremely important that _ALL_ code gets reviewed, no matter the complexity. If you make a PR to revert changes, I don't think it would need to be re-tested. It just needs to be reviewed to triple check the revert was done successfully and nobody thinks the changes will break the model.

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 13:40
Why do we need another PR? Isn't this just the problem of file/directories permission?
Can't you just set appropriate permissions to:

```
$ pwd
/scratch2/NAGAPE/epic

$ ls -l
total 28
drwxrwsrw-  3 Jong.Kim                   epic 4096 Aug  2 15:34 UFS-WM_RT
``

**Comment by jkbk2004** [comment] 2023-08-03 13:40
> @jkbk2004 There are applicable shortcuts to the process where you can make a "hotfix". It's extremely important that _ALL_ code gets reviewed, no matter the complexity. If you make a PR to revert changes, I don't think it would need to be re-tested. It just needs to be reviewed to triple check the revert was done successfully and nobody thinks the changes will break the model.

@BrianCurtis-NOAA I will create PR. So that you can confirm DISKNM=/scratch1/NCEPDEV/nems/role.epic/RT. If not working, then we can revert thru the PR.

**Comment by DeniseWorthen** [comment] 2023-08-03 13:44
@jkbk2004 I was thinking what Dusan was thinking...

I ran a single test to confirm the change to DISKNM worked for me.

**Comment by jkbk2004** [comment] 2023-08-03 13:44
> /scratch2/NAGAPE/epic

@DusanJovic-NOAA That's right. I need someone to confirm from different group. /scratch2/NAGAPE/epic is different project. Can you confirm to see if you can access /scratch2/NAGAPE/epic/UFS-WM_RT ?

**Comment by BrianCurtis-NOAA** [comment] 2023-08-03 13:47
Sorry for the confusion, what i'm talking about is the change to use the NGAPE location needs more testing/fixes potentially (so a PR would be appropriate), and the hotfix (using nems/role.epic/RT) just needs one PR for the changes. The third option as Dusan notes is also applicable, but I think Jong was saying the NGAPE permission problem might take a little while?

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 13:48
You should not make /scratch2/NAGAPE/epic/UFS-WM_RT world writable. This directory and all subdirectories and files should not be writable by anybody except the owner and maybe group.

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 13:49
```
$ ls -l /scratch2/NAGAPE/epic/UFS-WM_RT
total 12
-rw-r--r-- 1 Dusan.Jovic epic   16 Aug  3 13:47 I_SHOULD_NOT_BE_ABLE_TO_WRITE_TO_THIS_DIRECTORY
drwxrwsrwx 5 Jong.Kim    epic 4096 Aug  2 15:42 NEMSfv3gfs
-rwxrwxrwx 1 Jong.Kim    epic  765 Aug  1 20:56 adjust_permissions.sh
```

**Comment by BrianCurtis-NOAA** [comment] 2023-08-03 13:55
@DusanJovic-NOAA take a look now, perms look OK. @DeniseWorthen can we use current develop and see if permission are OK again?

**Comment by jkbk2004** [comment] 2023-08-03 13:58
If /scratch2/NAGAPE works, that's better solution, I think.  instead of /scratch1/NCEPDEV/nems/role.epic

**Comment by DeniseWorthen** [comment] 2023-08-03 14:02
We are making decisions and changes on the fly, without making sure everything works for everyone. I suggest reverting to the previous location and then moving forward later w/ a tested solution through PR etc.

**Comment by jkbk2004** [comment] 2023-08-03 14:06
We can move on if people from nems group can access.

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 14:06
Why are all files executable?

```
$ ls -l /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20230728/rrfs_v1beta_intel
total 2092856
-rwxrwxr-x 1 Jong.Kim epic   2707846 Aug  1 20:18 GFSFLX.GrbF00
-rwxrwxr-x 1 Jong.Kim epic   6022768 Aug  1 20:18 GFSFLX.GrbF09
-rwxrwxr-x 1 Jong.Kim epic   6220959 Aug  1 20:18 GFSFLX.GrbF12
-rwxrwxr-x 1 Jong.Kim epic  67857624 Aug  1 20:18 GFSPRS.GrbF00
-rwxrwxr-x 1 Jong.Kim epic  65500126 Aug  1 20:18 GFSPRS.GrbF09
-rwxrwxr-x 1 Jong.Kim epic  64902800 Aug  1 20:18 GFSPRS.GrbF12
drwxrwsr-x 2 Jong.Kim epic      4096 Aug  1 20:18 RESTART
-rwxrwxr-x 1 Jong.Kim epic 483652469 Aug  1 20:18 atmf000.nc
-rwxrwxr-x 1 Jong.Kim epic 483652469 Aug  1 20:18 atmf009.nc
-rwxrwxr-x 1 Jong.Kim epic 483652469 Aug  1 20:18 atmf012.nc
-rwxrwxr-x 1 Jong.Kim epic 159610053 Aug  1 20:18 sfcf000.nc
-rwxrwxr-x 1 Jong.Kim epic 159610053 Aug  1 20:18 sfcf009.nc
-rwxrwxr-x 1 Jong.Kim epic 159610053 Aug  1 20:18 sfcf012.nc
```

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 14:07
```
$ ls -l /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/develop-20230728/rrfs_v1beta_intel
total 2092856
-rw-r--r-- 1 emc.nemspara nems   2707846 Jul 31 13:03 GFSFLX.GrbF00
-rw-r--r-- 1 emc.nemspara nems   6022768 Jul 31 13:03 GFSFLX.GrbF09
-rw-r--r-- 1 emc.nemspara nems   6220959 Jul 31 13:03 GFSFLX.GrbF12
-rw-r--r-- 1 emc.nemspara nems  67857624 Jul 31 13:03 GFSPRS.GrbF00
-rw-r--r-- 1 emc.nemspara nems  65500126 Jul 31 13:03 GFSPRS.GrbF09
-rw-r--r-- 1 emc.nemspara nems  64902800 Jul 31 13:03 GFSPRS.GrbF12
drwxr-sr-x 2 emc.nemspara nems      4096 Jul 31 13:03 RESTART
-rw-r--r-- 1 emc.nemspara nems 483652469 Jul 31 13:03 atmf000.nc
-rw-r--r-- 1 emc.nemspara nems 483652469 Jul 31 13:03 atmf009.nc
-rw-r--r-- 1 emc.nemspara nems 483652469 Jul 31 13:03 atmf012.nc
-rw-r--r-- 1 emc.nemspara nems 159610053 Jul 31 13:03 sfcf000.nc
-rw-r--r-- 1 emc.nemspara nems 159610053 Jul 31 13:03 sfcf009.nc
-rw-r--r-- 1 emc.nemspara nems 159610053 Jul 31 13:03 sfcf012.nc
```

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 14:11
Also why is all this owned by Jong.Kim instead of some role account, for example role.epic?

**Comment by jkbk2004** [comment] 2023-08-03 14:15
Unfortunately, role.epic was allocated under nems at /scratch1/NCEPDEV/nems/role.epic not separate epic project /scratch2/NAGAPE/epic. Ideally it should be under role account and separate epic project. I can request to move role.epic to /scratch2/NAGAPE/

**Comment by DusanJovic-NOAA** [comment] 2023-08-03 14:24
So why are you moving from a directory owned by role.epic to the directory owned by you? What's the point.
Also it looks like you just did recursive copy instead of rsyncing from the original location, all time stamps are changed to Aug 1, see for example input directory.

**Comment by jkbk2004** [comment] 2023-08-03 14:32
To better handle permission issues, EPIC requested to maintain RTs under epic project. Otherwise, epic people will continuously need to ask permission to emc nems project.

**Comment by jkbk2004** [comment] 2023-08-03 14:37
Let me try rsync to correctly reset file permissions.

**Comment by jkbk2004** [comment] 2023-08-03 16:34
@SadeghTabas-NOAA confirms RT with develop branch runs ok on his side. @jiandewang Can you double check?

**Comment by jiandewang** [comment] 2023-08-03 16:41
> @SadeghTabas-NOAA confirms RT with develop branch runs ok on his side. @jiandewang Can you double check?

@jkbk2004 I don't see any commit related email, did you just change the permission for that fixed file directory ?

**Comment by jkbk2004** [comment] 2023-08-03 16:51
> > @SadeghTabas-NOAA confirms RT with develop branch runs ok on his side. @jiandewang Can you double check?
> 
> @jkbk2004 I don't see any commit related email, did you just change the permission for that fixed file directory ?

I changed permission and @SadeghTabas-NOAA runs ok. But I need you to confirm one more time.

**Comment by jiandewang** [comment] 2023-08-03 16:56
> > > @SadeghTabas-NOAA confirms RT with develop branch runs ok on his side. @jiandewang Can you double check?
> > 
> > 
> > @jkbk2004 I don't see any commit related email, did you just change the permission for that fixed file directory ?
> 
> I changed permission and @SadeghTabas-NOAA runs ok. But I need you to confirm one more time.

OK let me try that

**Comment by jiandewang** [comment] 2023-08-03 17:15
now I have access to the fixed file directory, my jobs are running

**Comment by jiandewang** [comment] 2023-08-03 17:30
now baseline results are at /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20230728/
but inside this directory there is another develop-20230728 directory, is this correct ? I don't understand how comes @SadeghTabas-NOAA runs are OK ? Or am I missed anything in my run ? I changed nothing in rt.sh

**Comment by jkbk2004** [comment] 2023-08-03 17:32
> now baseline results are at /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20230728/ but inside this directory there is another develop-20230728 directory, is this correct ? I don't understand how comes @SadeghTabas-NOAA runs are OK ? Or am I missed anything in my run ? I changed nothing in rt.sh

@jiandewang fixed! Submit again, please.

**Comment by sadeghitabas** [comment] 2023-08-03 18:07
> now baseline results are at /scratch2/NAGAPE/epic/UFS-WM_RT/NEMSfv3gfs/develop-20230728/ but inside this directory there is another develop-20230728 directory, is this correct ? I don't understand how comes @SadeghTabas-NOAA runs are OK ? Or am I missed anything in my run ? I changed nothing in rt.sh

@jiandewang I ran a single reg test (control_c48) against baseline using current develop branch and it was successful. thanks.

**Comment by jiandewang** [comment] 2023-08-03 19:06
@jkbk2004 my re-run works fine now.

**Comment by jkbk2004** [comment] 2023-08-03 19:22
@jiandewang Cool! Sorry for interruption. I am closing this issue.

**Closed as completed by jkbk2004** 2023-08-03 19:22 UTC
Labels: bug
