### ISSUE TITLE
Parallel IO issue

### ISSUE THREAD

**Issue by Hae-CheolKim** [ufs-community/ufs-weather-model#1234] opened 2022-05-26 15:18 UTC
## Description

With the new compilation I cloned on May 23, 2002, I advanced a run for 1/12-th degree DATM (CDEPS)-MOM6-CICE6 on HERA but bumped into an parallel IO issue. Looks like this has something to do with parallel netcdf lib.

...
   0: Abort with message NetCDF: Variable not found in file /scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pio_nc.c at line 1158
  40: Abort with message NetCDF: Variable not found in file /scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pio_nc.c at line 1158
   1: Abort with message NetCDF: Variable not found in file /scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pio_nc.c at line 1158
   2: Abort with message NetCDF: Variable not found in file /scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pio_nc.c at line 1158
  41: Abort with message NetCDF: Variable not found in file /scratch2/NCEPDEV/nwprod/hpc-stack/src/develop/pkg/pio-2.5.3/src/clib/pio_nc.c at line 1158
...

### To Reproduce:
What compilers/machines are you seeing this with? INTEL/HERA
Give explicit steps to reproduce the behavior.

1. Compile the model code at /scratch2/NCEPDEV/marine/Hae-Cheol.Kim/ufs-weather-model
2. run the test case /scratch1/NCEPDEV/stmp2/Hae-Cheol.Kim/FV3_RT/rt_191768/GLBb0.08_038_gefs 

## Additional context
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- needs to be fixed also in noaa-emc/nems/issues/<issue_number>
- needed for noaa-emc/fv3atm/pull/<pr_number>

**Comment by DeniseWorthen** [comment] 2022-09-12 15:47
What is the status of this issue?

**Comment by Hae-CheolKim** [comment] 2022-09-12 16:06
Not resolved, yet.

**Comment by arunchawla-NOAA** [comment] 2023-02-15 12:53
@edwardhartnett bringing to your attention. Do you have any suggestions for @Hae-CheolKim-NOAA

**Comment by edwardhartnett** [comment] 2023-02-15 13:06
This is a PIO error, not a netCDF error.

Have we tried with the latest release of PIO and netCDF?

It's complaining about a variable not found, what are the lines of code which are being called?

Is there a test code that demonstrates this problem? If not, could you generate one please? That is, a single-file Fortran program which does the same thing the model is doing, and generates the same error?

**Comment by Hae-CheolKim** [comment] 2023-02-17 14:15
I tested the new src cloned on Feb 15, 2023, this issue was not repeated and I was able to compile and initialize the 1/12-th degree DATM (CDEPS)-MOM6-CICE6 on HERA. Sorry for the delay in updating the status and thanks for your support.

**Comment by junwang-noaa** [comment] 2023-03-27 13:26
@Hae-CheolKim-NOAA It looks to me the issue is resolved. Can we close it?

**Comment by Hae-CheolKim** [comment] 2023-03-27 13:28
Yes, please. Thanks!

**Closed as completed** 2023-03-27 13:32 UTC
Labels: bug
