### ISSUE TITLE
ufs-weather-model rt.sh failed on GAEA

### ISSUE THREAD

**Issue by jiandewang** [ufs-community/ufs-weather-model#1724] opened 2023-04-25 20:28 UTC
## Description

Now GAEA C4 is back, but rt.sh failed to run although compiling is fine. 
Error information can be seem at 
/lustre/f2/scratch/ncep/Bin.Li/FV3_RT/rt_16530/datm_cdeps_iau_gefs/err

Lmod has detected the following error: The following module(s) are unknown:
"intel/2021.3.0"

Please check the spelling or version number. Also try "module spider ..."
It is also possible your cache file is out-of-date; it may help to try:
  $ module --ignore_cache load "intel/2021.3.0"

Note it is run under account with default shell of bash (Thanks for Bin Li's help)

### To Reproduce:

clone latest ufs-weather-model
run rt.sh 
then see the "err" file inside run directory

**Comment by JustinPerket** [comment] 2023-04-26 13:25
I was also having trouble yesterday on Gaea with the C4 update, and had opened a ticket with their helpdesk

**Comment by jkbk2004** [comment] 2023-04-26 13:27
@jiandewang @JustinPerket I am tracking this Gaea issue today. I think I need to confirm lmod issue again. @natalie-perlin FYI

**Comment by JustinPerket** [comment] 2023-04-26 13:38
@jkbk2004 ok, let me know if you want to be forwarded anything. HT to Kris Rand here, reviewing the  20 March 2023 resource Gaea email and attached google doc was helpful in understanding the changes.

**Comment by zach1221** [comment] 2023-04-28 00:38
Below is a screen shot of the error after attempting two UFS-WM RTs. (cpld_control_c48 & cpld_control_p8_faster) I'm happy to help test/investigate this issue further.
![image](https://user-images.githubusercontent.com/99902696/235023128-5d293b8d-a809-4953-879e-1f6e15393b34.png)

**Comment by JustinPerket** [comment] 2023-04-28 14:29
Not to rush, but any progress on getting this fixed? 
If needed, below is the doc previously mentioned:

docs.google.com/document/d/1YabQ3ZljYRVFyilIG6fimyFd-TaHkDxHtz6ScPZrYzw/

I'm not sure if this is useful or not, but I saw that (as of 2-3 days ago),  `/lustre/f2/dev/role.epic/contrib/Lmod_init.sh` has:

```shell
echo "Initializing lua module environment Lmod 8.7.12, loading modules (wait...)"
export LMOD_SYSTEM_DEFAULT_MODULES=modules/3.2.11.4
```

When trying to look into things using the login nodes, we at GFDL noted that gaea13 (now called the only C4 head node) only has `modules/3.2.6.7`, whereas gaea10-14 still also has `modules/3.2.11.1`, `modules/3.2.11.4 (default)`, and `modules/4.1.3.1` from /opt/cray/pe/modulefiles. This lead to a bit of confusion on my part peeking at things on the logins.

**Comment by natalie-perlin** [comment] 2023-04-28 17:54
@jiandewang  - It looks like Lmod initialization issue, as the environment does not seem correct in the log. There is a good discussion on this topic here ( https://github.com/ufs-community/ufs-weather-model/issues/1683#issuecomment-1508796149), as yes - indeed- it's a bit different process that on other systems because we use EPIC-installed Lmod.
Could you please make a _fresh login_ to Gaea, so you have the default modules loaded. 

Update (Got the issue about C4 node!): I'll change the hard-coded 
`export LMOD_SYSTEM_DEFAULT_MODULES=modules/3.2.11.4`
to simply 
`export LMOD_SYSTEM_DEFAULT_MODULES=modules`
and test it... will let you know whether this could be a solution!

**Comment by natalie-perlin** [comment] 2023-04-28 18:16
@jiandewang @zach1221 - it appears that the C4 login node has `Lmod `as the system module manager, not via modules/x.x.x . Let me find a workaround that would work for all of the nodes.

You could query the $MODULESHOME variable upon login to find this out:

`echo $MODULESHOME`
The prompt on gaea12 is /opt/cray/pe/modules/3.2.11.4
The prompt on gaea13/C4 is /usr/share/lmod/lmod

**Comment by natalie-perlin** [comment] 2023-04-28 23:41
@jiandewang @jkbk2004 @zach1221 - 
A script for Lmod initialization for Gaea has been updated to accommodate different hosts that may have different module management software. The script name has remained the same: /lustre/f2/dev/role.epic/contrib/Lmod_init.sh
(Please note that you may need a fresh login so that all default scripts are loaded with no other extras or purges)

Depending on the login node, Gaea could have the following module management software: 
 1) modules/3.2.11.4 (or any other default version, gaea12 and below)
  2)  Lmod version 8.3.1 (gaea13, C4)
  3) Lmod version 8.7.15 (C5)
  
  EPIC's installed Lmod is 8.7.12. If the host has option 1. or 2. from the above list, EPIC's Lmod is initialized. If it's option 3., it leaves higher Lmod and does not uses EPIC's lower version.
  
  Please let me know if you find any unexpected behavior.
  The older Lmod_init.sh has been saved with the name Lmod_init.sh_old

**Comment by jiandewang** [comment] 2023-04-29 00:27
@natalie-perlin I just had a try (login node is gaea12) by following discussion and steps at https://github.com/ufs-community/ufs-weather-model/discussions/1666#discussioncomment-5665556), now I got cmake/3.20.1 module load problem again. In the past several days that issue was gone and I can at least got compiling job done.

_Lmod has detected the following error: These module(s) or extension(s) exist
but cannot be loaded as requested: "alps", "cmake/3.20.1"_

see /lustre/f2/scratch/ncep/Jiande.Wang/FV3_RT/rt_30089/compile_001/out
_gaea10_
_Lmod version is greater than or equal to EPIC installed 8.7.12_

**Comment by natalie-perlin** [comment] 2023-04-29 08:06
@jiandewang - 
There is something going on with Gaea hosts, a test RT compile job failed after connection issue with the host. At the moment, however, I was able to successfully compile the WM code interactively, e.g. loading the modules, setting the CMAKE flags, and building the code.
source /lustre/f2/dev/role.epic/contrib/Lmod_init.sh
module use <ufs-weather-model>/modulefiles
export CMAKE_FLAGS="-DAPP=S2S -DCCPP_SUITES=FV3_GFS_v17_coupled_p8" 
./build.sh 2>&1 | tee build.interactive.log

The log could be found: /lustre/f2/dev/role.epic/sandbox/UFS-WM/ufs-wm-dev/build.interactive.log
A build directory: /lustre/f2/dev/role.epic/sandbox/UFS-WM/ufs-wm-dev/build_interactive

Will keep an eye on what's going on with Gaea. From the user's perspective and logging to hostname=gaea10, nothing should have changed in Lmod initialization steps, but will keep it open to further improvements.
Could you also please post your steps (to reproduce the issue), starting from login, then query "echo $0", and then other steps to submit a job or initialize Lmod .

**Comment by jiandewang** [comment] 2023-05-01 02:37
@natalie-perlin what you tried is interactive way while I am doing batch style as I need to run several dozen of jobs in one shot. So whatever module setup you did on login node will have no effect on the node where batch job will be running, and I think this is the problem we are facing.

**Comment by jiandewang** [comment] 2023-05-01 02:46
these are steps I did

- login to GAEA, echo $0 will get tcsh
- switch to bash
- git clone https://github.com/ufs-community/ufs-weather-model
- cd ufs-weather-model
- source /lustre/f2/dev/role.epic/contrib/Lmod_init.sh
- module use modulefiles
- module load ufs_gaea.intel
- cd test
- modify rt.sh, line 368 to your project account, for me, it is nggps_emc
- nohup ./rt.sh -e>output&  this will do all the compiling and run UFS jobs but will be on different node rather than the login node

**Comment by natalie-perlin** [comment] 2023-05-01 13:33
@jiandewang - 
   as a side note - you do not need to load the modulefiles if you run the rt.sh. 
   Loading the modulefiles are needed only if you compile interactively. 
  Since you submit the rt.sh, it will use the tcsh in batch jobs.
  
So we have actually three issues here for Gaea:
1) different module management software (or versions) on C3, C4, and C5 (may not yet be used, but tested)
2) no intel/2021.3.0 available on C4 (or C5)
3) updated Lmod loads the default files on all three partitions, but no longer works with the tcsh being a default.

 @jkbk2004 - could we discuss it, what would be the best ways to solve it, from the UFS users' perspective, and what could be requested from the system administrators?

**Comment by bensonr** [comment] 2023-05-01 18:40
Things to consider post software upgrade specific to the C4 slurm cluster
 1) the gaea modules environment will need to be updated to be compatible with C4 software versions.
 2) Intel 18 and 19 are no longer available - only OneAPI versions
 3) The HPC/Spack Stack may need to be updated to use the OneAPI Intel compilers
 4) PrgEnv-intel/6.0.10-classic must be used with intel-classic modules in order to build with legacy ifort via the HPE ftn wrapper
 5) The _es_ cluster now has separate partitions for the different login nodes.  This means in order to compile on a c4 login node, you muse use the the _eslogin_c4_ partition modifier in the build script template.
 6) If you want to continue to use the Intel 18 or 19 compilers to build software, you must use the _eslogin_c3_ partition modifier
 7) The executables you build will still be statically linked and need no modules to satisfy library references at runtime.

**Comment by natalie-perlin** [comment] 2023-05-01 20:50
> Things to consider post software upgrade specific to the C4 slurm cluster
> 
> 1. the gaea modules environment will need to be updated to be compatible with C4 software versions.
> 2. Intel 18 and 19 are no longer available - only OneAPI versions
> 3. The HPC/Spack Stack may need to be updated to use the OneAPI Intel compilers
> 4. PrgEnv-intel/6.0.10-classic must be used with intel-classic modules in order to build with legacy ifort via the HPE ftn wrapper
> 5. The _es_ cluster now has separate partitions for the different login nodes.  This means in order to compile on a c4 login node, you muse use the the _eslogin_c4_ partition modifier in the build script template.
> 6. If you want to continue to use the Intel 18 or 19 compilers to build software, you must use the _eslogin_c3_ partition modifier
> 7. The executables you build will still be statically linked and need no modules to satisfy library references at runtime.

Thank you for your comments. 
The issue appears is that it does not seem the compiler intel/2021.3.0 is available on c4 either. Our software stacks for C3 were built with that compiler. 
In addition to the default modules that include PrgEnv-intel/6.0.5, following modules are loaded to build the software stack on Gaea:
module load intel/2021.3.0
module load cray-mpich/7.7.11

**Comment by natalie-perlin** [comment] 2023-05-01 21:06
@jiandewang - could you please test your rt.sh submission again, testing the default tcsh? The Lmod_init.sh has been updated.
Please note that this fix does not resolve the C4 issue, as there is no compiler available. The stack need to be rebuilt to use compilers that are present on both C3 and C4.

**Comment by jiandewang** [comment] 2023-05-02 02:08
@natalie-perlin run rt.sh using default tcsh yield no error but job finished in seconds, virtually it didn't do anything. You may see output at
/lustre/f2/dev/ncep/Jiande.Wang/MOM6-update/20230406/0428/ufs-weather-model/tests/output

can you do a quick test under your account ?
(1) cp -r /lustre/f2/dev/ncep/Jiande.Wang/MOM6-update/20230406/0428/ufs-weather-model
(2) cd ufs-weather-model/test
(3) modify line 368 of rt.sh to use your project account
(4) ./rt.sh -kl rt.conf-test>output

**Comment by natalie-perlin** [comment] 2023-05-02 03:56
@jiandewang (NB: @zach1221 )
- The steps done (similar to those @jiandewang suggested but not exact):
1) cp -r /lustre/f2/dev/ncep/Jiande.Wang/MOM6-update/20230406/0428/ufs-weather-model .
2) cd ufs-weather-model/tests
3) rm -rf ecflow_run/
4) modified line 368 of rt.sh
5)  ./rt.sh -k -e -l rt.conf-test >& output.log1 &

After a short wait, checked the log files:
6) cd log_gaea.intel
7) view compile_001.log  - competed, "Elapsed time 367 seconds. Compile 001"
8) rt_001_datm_cdeps_control_cfsr.log: "Test 001 datm_cdeps_control_cfsr FAIL"
9) checked the RUNDIR_ROOT in run_001_datm_cdeps_control_cfsr.log, 
RUNDIR_ROOT=/lustre/f2/scratch/role.epic/FV3_RT/rt_27842
10) cd <RUNDIR_ROOT> ; cd datm_cdeps_control_cfsr
11) view err - 
     shows the changes in loaded modules, as it appears to be on C4 partition with different modules, and then subsequently fails with this error: 

```
These module(s) or extension(s) exist
but cannot be loaded as requested: "intel/2021.3.0"
   Try: "module spider intel/2021.3.0" to see how to load the module(s).
```

And yes, this is expected because a partiton c4 was requested, on which no intel/2021.3.0 is installed. Verify it as following:

```
ssh gaea13
module avail intel
```

Prompt:

```
---------------------------- /opt/cray/pe/lmod/modulefiles/core ----------------------------
   PrgEnv-intel/6.0.10-classic (L,D)    intel-classic/2022.2.1 (L,D)    intel/2022.0.2
   PrgEnv-intel/6.0.10                  intel-oneapi/2022.0.2           intel/2022.2.1 (D)
   intel-classic/2022.0.2               intel-oneapi/2022.2.1  (D)

```

**Compilation** is done on `partition=eslogin` , as appears from
/lustre/f2/scratch/role.epic/FV3_RT/rt_27842/compile_001/job_card , 
and completed on a host gaea9, see /lustre/f2/scratch/role.epic/FV3_RT/rt_27842/compile_001/out. 

**Test run** was submitted to `partition=c4`, as appears from 
/lustre/f2/scratch/role.epic/FV3_RT/rt_27842/datm_cdeps_control_cfsr/job_card.
No intel/2021.3.0 on c4!

**Comment by natalie-perlin** [comment] 2023-05-02 13:34
A new stack built on **C3 login** node is built on **Gaea** with **intel/intel-classic.2022.0.2**, **cray-mpich/7.7.11**, **PrgEnv-intel/6.0.5**.

On **C4**, the corresponding intel compiler module name is  **intel-classic/2022.0.2**, and mpich available is **cray-mpich/7.7.20**, **PrgEnv-intel/6.0.10**

`/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/stack`

Because of the different compiler names and mpich (and PrgEnv-intel) versions on C3 and C4, these modules need to be loaded explicitly, and are no longer labeled as "required" in hpc-metamodules.

There is still a challenge on how to load the intel compiler in `ufs_gaea.intel.lua` depending on whether it is done on C3 or C4, because of the different names, intel/intel-classic.2022.0.2 vs. intel-classic/2022.0.2. 

This is [partially] relevant to https://github.com/ufs-community/ufs-weather-model/discussions/1666

**Comment by JustinPerket** [comment] 2023-05-02 13:46
Thank you for continuing to work on this.  I heard that there are other GFDL UFS users with helpdesk tickets open, and ORNL has been made aware of them.


> 
> **Test run** was submitted to `partition=c4`, as appears from /lustre/f2/scratch/role.epic/FV3_RT/rt_27842/datm_cdeps_control_cfsr/job_card. No intel/2021.3.0 on c4!

Correct me if I'm wrong, but from my limited understanding, this seems to match what was in the the March 20th proposed changes. In maybe not the most direct way, it seems to say that these intel versions were slated to not be included in the update for C4 to match C5 PrgEnvs:

> 18.0.6.288
> 19.0.5.281
> 19.1.1.217
> 19.1.4.304
> 2021.2.0 (classic and oneapi)
> 2021.3.0 (classic and oneapi)

(there may be an unfortunate typo. The doc listed `2021.0.3`, but I think it was meant to be `2021.3.0`

**Comment by natalie-perlin** [comment] 2023-05-02 14:03
@JustinPerket -
   excellent, thanks for the note about March 20 message and doc on the changes. It indeed mentioned intel 2021 being removed, not only 18.x and 19.x.

**Comment by bensonr** [comment] 2023-05-02 14:19
One other update that is still under discussion regarding c3, it will either be updated to the same level of software as c4 or it will be retired.  So make the decisions on platform support with that in mind.

**Comment by jkbk2004** [comment] 2023-05-02 14:44
intel-2022.02 looks to be most practical option.

**Comment by jswhit** [comment] 2023-05-02 15:43
just tried building on gaea with intel.2022.0.2  and got this error:

ld: /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/intel-2022.0.2/cray-mpich-7.7.11/esmf/8.3.0b09/lib/libesmf.a(ESMCI_MethodTable.o): in function `ESMCI::MethodElement::resolve()':
/lustre/f2/dev/role.epic/contrib/hpc-stack/src-intel-2022.0.2/pkg/v8.3.0b09/src/Superstructure/Component/src/ESMCI_MethodTable.C:400: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
ld: attempted static link of dynamic object `/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/intel-2022.0.2/jpeg/9.1.0/lib/libjpeg.so'

**Comment by natalie-perlin** [comment] 2023-05-02 18:58
**UPDATE: Need to rebuild the stack to resolve all the dependencies for jpeg and zlib (built as static libraries)**

@jswhit - Thanks for checking it, fixed now! Jpeg was compiled as "shared" library. It needs to be static. Before the fix:
```
ls -lt /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/intel-2022.0.2/jpeg/9.1.0/lib
-rwxr-xr-x 1 role.epic wpo 563664 May  2 14:53 libjpeg.so
```
After the fix:
`-rw-r--r-- 1 role.epic wpo 625228 May  2 14:55 libjpeg.a`

(Need to quickly fix it in other more recently built stacks)

**Comment by jswhit** [comment] 2023-05-02 21:33
Thanks @natalie-perlin.  Now the problem is I can't load  hpc-intel/2022.0.2.  It's trying to load intel/2022.0.2 which fails because the module is actually named intel/intel.2022.0.2 (on gaea15 at least)

Executing this command requires loading "intel/2022.0.2" which failed while processing the following module(s):

    Module fullname     Module Filename
    ---------------     ---------------
    hpc-intel/2022.0.2  /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/core/hpc-intel/2022.0.2.lua
While processing the following module(s):
    Module fullname     Module Filename
    ---------------     ---------------
    hpc-intel/2022.0.2  /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/core/hpc-intel/2022.0.2.lua

**Comment by natalie-perlin** [comment] 2023-05-02 21:35
> Thanks @natalie-perlin. Now the problem is I can't load hpc-intel/2022.0.2. It's trying to load intel/2022.0.2 which fails because the module is actually named intel/intel.2022.0.2 (on gaea15 at least)
> 
> Executing this command requires loading "intel/2022.0.2" which failed while processing the following module(s):
> 
> ```
> Module fullname     Module Filename
> ---------------     ---------------
> hpc-intel/2022.0.2  /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/core/hpc-intel/2022.0.2.lua
> ```
> 
> While processing the following module(s): Module fullname Module Filename --------------- --------------- hpc-intel/2022.0.2 /lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/core/hpc-intel/2022.0.2.lua

@jswhit Please hold on!.. Rebuilding it fully, due to too many dependencies to resolve.

**Comment by natalie-perlin** [comment] 2023-05-03 06:03
Rebuilt the stack with intel/intel-classic.2022.0.2
`/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/stack`

@jswhit - Please note, the warnings about "ldopen..." still generated because esmf is being compiled with the "shared" option, but these are not errors. 

The `ufs_gaea.intel.lua` modulefile could look like the one below, to allow loading modules on both C3 and C4.
```
help([[
  This module loads libraries required for building and running UFS Weather Model 
  on the NOAA RDHPC machine Gaea using Intel-2022.0.2
]])

whatis([===[Loads libraries needed for building the UFS Weather Model on Gaea ]===])

load_any(pathJoin("cmake", os.getenv("cmake_ver") or "3.20.1"),"cmake")

prepend_path("MODULEPATH","/lustre/f2/dev/role.epic/contrib/hpc-stack/intel-2022.0.2/modulefiles/stack")
load(pathJoin("hpc", os.getenv("hpc_ver") or "1.2.0"))

local intel1="intel/intel-classic." .. (os.getenv("intel_ver") or "2022.0.2")
local intel2="intel/" .. (os.getenv("intel_ver") or "2022.0.2")
load_any(intel1,intel2)
load_any(pathJoin("cray-mpich", os.getenv("cray_mpich_ver") or "7.7.11"),"cray-mpich")
load(pathJoin("hpc-intel", os.getenv("hpc_intel_ver") or "2022.0.2"))
load(pathJoin("hpc-cray-mpich", os.getenv("hpc_cray_mpich_ver") or "7.7.11"))
load(pathJoin("libpng", os.getenv("libpng_ver") or "1.6.37"))

-- Needed at runtime:
load("alps")

load("ufs_common")

setenv("CMAKE_Platform","gaea.intel")
```

Tested building the UFS-WM on login nodes using ./build.sh script:
1. Building on c3  login node works OK. 
2. With all the Intel and cray-mpich modules loaded properly, building it on c4  login node (gaea13) still produces CMake error:
```
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS)
CMake Error at /ncrc/sw/gaea-cle7/uasw/ncrc/envs/20200417/opt/linux-sles15-x86_64/gcc-7.5.0/cmake-3.20.1-w7tkahac22qulhbcbi6io54u5dfr36zs/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_C_FOUND) (found version "3.1")
```

Please let me know any comments!

**Comment by natalie-perlin** [comment] 2023-05-03 15:15
The actual issue (a help request sent to GFDL): 

With all the module loaded, the MPI compilers used to be set as following on Gaea:
setenv("MPI_FC",  "ftn")
setenv("MPI_CC",  "cc")
setenv("MPI_CXX", "CC")

These settings may need to be different for the c4 (?) - waiting for the help from GFDL!

**Comment by jkbk2004** [comment] 2023-05-12 20:21
gaea baseline was recovered with #1749

**Closed as completed by jkbk2004** 2023-05-12 20:21 UTC
Labels: bug
