### ISSUE TITLE
commit RT log file to user's branch using autort

### ISSUE THREAD

**Issue by junwang-noaa** [ufs-community/ufs-weather-model#997] opened 2022-01-05 02:58 UTC
## Description
It is found that sometimes the autort can't commit the RT log files to user's branch. It was suggested that using "ssh://git@github.com " instead of "https://github.com" to clone user's branch may help resolve the issue.  An update is needed in autort to implement this approach with github API.

## Additional context
When an update is ready, a ufs-weather-model PR will be created.

**Comment by BrianCurtis-NOAA** [comment] 2022-01-24 14:17
I've updated AutoRT to use SSH for git clones and pushes and pulls. There were no issues with RT jobs, but BL jobs seemed to have issues, but it's unknown if it was related to these code changes or not. I will wait for a few more BL change PRs to go through the commit queue before closing this.

**Comment by BrianCurtis-NOAA** [comment] 2022-01-24 15:29
The issue was specific to Orion and the code is no longer necessary, so I've removed it. All BL tasks should run (minus machine issues) OK. Once I see a BL PR completed without AutoRT issues I will close this issue.

**Comment by MinsukJi-NOAA** [comment] 2022-01-24 15:38
> The issue was specific to Orion and the code is no longer necessary, so I've removed it. All BL tasks should run (minus machine issues) OK. Once I see a BL PR completed without AutoRT issues I will close this issue.

For the latest trial of auto BL creation on #1009, the auto process stopped after generating BL but before copying them onto the baseline location. However, the created BL's were not deleted, allowing me to copy them manually.

**Comment by SamuelTrahanNOAA** [comment] 2022-01-24 16:53
It was my account that consistently broke AutoRT due to this problem (probably) and I suggested the `ssh:git@github.com`. That's because the github documentation claims Enterprised-Managed Accounts with mandatory two-factor authentication can only be written by ssh, not https. Next time you merge one of my PRs, we should know if it fixes the problem.

**Comment by SamuelTrahanNOAA** [comment] 2022-01-24 16:55
@grantfirl If you can have me do the ufs-weather-model PR for an answer-changing ccpp/physics PR, I can test this fix.

**Comment by junwang-noaa** [comment] 2022-03-04 20:28
@BrianCurtis-NOAA Is the issue resolved?

**Comment by BrianCurtis-NOAA** [comment] 2022-03-04 20:53
The goal was to use SSH instead of HTTPS for git clones to fix an permissions issue. The fix was made but in the end there seems to be no way to guarantee a safe push to a users branch without having collaborator permissions in their fork.

The issue is and isn't resolved. But for the purposes of why this issue was created I feel we can close it since I don't think it's an issue with AutoRT or UFS, but with github and how they handle PR's.

**Closed as completed** 2022-03-04 21:44 UTC
Labels: bug
