### ISSUE TITLE
can not run single test using rt.sh

### ISSUE THREAD

**Issue by WChen-NOAA** [ufs-community/ufs-weather-model#2192] opened 2024-03-14 16:58 UTC
## Description
can not run single test using rt.sh

### To Reproduce:
1.  /rt.sh -l rt.conf -n control_p8 intel -a $ACCNR
2. then failed with err.msg: 
'The -n option needs <testname> AND <compiler> in quotes, i.e. -n "control_p8 intel"'
3. then tried /rt.sh -l rt.conf -n "control_p8 intel" -a $ACCNR
run all regression tests.

**Comment by BrianCurtis-NOAA** [comment] 2024-03-14 17:01
Thanks for this issue Wen. I believe without the `-l rt.conf` it will run only that one test. But, the issue is that when the user specifies -l and -n it should run the test using that specified conf file, which is a use case that I know I haven't tested for.

**Comment by uturuncoglu** [comment] 2024-03-15 04:36
@BrianCurtis-NOAA JFYI, we are always using `-l` and `-n` together under `ufs-coastal` without any issue. But of course, we did not sync `ufs-coastal` recently and I think that "control_p8 intel" usage is new. So, maybe the update in RT system break that capability. If so we might need to fix it since `ufs-coastal` has its own test file called as `rt_coastal.conf` at this point. Anyway, once i synced `ufs-coastal` again, I'll check and report back.

**Comment by FernandoAndrade-NOAA** [comment] 2024-04-18 19:13
Leaving a note here that the current develop works fine running a single test with -n and without -l in a recent test on gaea at
`/gpfs/f5/epic/scratch/Fernando.Andrade-maldonado/reg-test/wm/dev-test/ufs-weather-model/tests/logs/RegressionTests_gaea.log`

Please ignore the error itself in the log, that's a system issue.
test was run with `./rt.sh -a epic -e -c -n "regional_spp_sppt_shum_skeb intel"`

**Comment by zach1221** [comment] 2024-04-23 16:57
I think a fix for this has been found, as seen in issue [2244](https://github.com/ufs-community/ufs-weather-model/issues/2244), so this can be closed once the commit is in develop.

**Comment by zach1221** [comment] 2024-04-26 15:06
Closing as UFS-WM PR #2241 has been merged.

**Closed as completed by zach1221** 2024-04-26 15:06 UTC
Labels: bug, EPIC Support Requested
