### ISSUE TITLE
Part of surface fields are missing in RESTART files for RRFS cases

### ISSUE THREAD

**Issue by hu5970** [ufs-community/ufs-weather-model#1655] opened 2023-03-14 17:09 UTC
## Description

We are testing the develop branch with RRFS cycles for on-going code merging efforts. We found that the part of the surface fields are filled with missing values in the restart file when using the develop branch. This will crash the following-up warm start runs.

Here are list of LSM variables with missing values in the RESTART sfc_data.nc:

clw_surf_land
cls_surf_ice
qwv_surf_land
qwv_surf_ice
sfcalb_land
sfcalb_land_bck
sfcalb_ice
tsnow_land
tsnow_ice
zorll
zorli

Something wrong with the develop branch when writing restart surface files. We are using RUCLSM.

**Comment by junwang-noaa** [comment] 2023-03-14 17:28
@yangfanglin @ligiabernardet  @MatthewPyle-NOAA Can we ask RUC LSM developers to take a look? Thanks

**Comment by tanyasmirnova** [comment] 2023-03-14 18:19
The problem is in the restart_write in FV3GFS_io.F90. The code that is not working correctly is:      
 if (Model%lsm == Model%lsm_ruc) then
         !--- Extra RUC variables
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%wetness)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%clw_surf_land)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%clw_surf_ice)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%qwv_surf_land)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%qwv_surf_ice)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%tsnow_land)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%tsnow_ice)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%snowfallac_land)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%snowfallac_ice)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%sfalb_lnd)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%sfalb_lnd_bck)
         call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%sfalb_ice)
         if (Model%rdlai) then
           call copy_from_GFS_Data(ii1,jj1,isc,jsc,nt,sfc_var2,Sfcprop(nb)%xlaixy)
         endif
....
Similar code in RRFS_dev branch looks like:
        if (Model%lsm == Model%lsm_ruc) then
          !--- Extra RUC variables
          sfc_var2(i,j,nvar2m+19) = Sfcprop(nb)%wetness(ix)
          sfc_var2(i,j,nvar2m+20) = Sfcprop(nb)%clw_surf_land(ix)
          sfc_var2(i,j,nvar2m+21) = Sfcprop(nb)%clw_surf_ice(ix)
          sfc_var2(i,j,nvar2m+22) = Sfcprop(nb)%qwv_surf_land(ix)
          sfc_var2(i,j,nvar2m+23) = Sfcprop(nb)%qwv_surf_ice(ix)
          sfc_var2(i,j,nvar2m+24) = Sfcprop(nb)%tsnow_land(ix)
          sfc_var2(i,j,nvar2m+25) = Sfcprop(nb)%tsnow_ice(ix)
          sfc_var2(i,j,nvar2m+26) = Sfcprop(nb)%snowfallac_land(ix)
          sfc_var2(i,j,nvar2m+27) = Sfcprop(nb)%snowfallac_ice(ix)
          sfc_var2(i,j,nvar2m+28) = Sfcprop(nb)%sfalb_lnd(ix)
          sfc_var2(i,j,nvar2m+29) = Sfcprop(nb)%sfalb_lnd_bck(ix)
          sfc_var2(i,j,nvar2m+30) = Sfcprop(nb)%sfalb_ice(ix)
          if (Model%rdlai) then
            sfc_var2(i,j,nvar2m+31) = Sfcprop(nb)%xlaixy(ix)
          endif
This code works fine in RRFS. 
....
It should be investigated why the I/O in ufs community code does not work properly  with RUC LSM.

**Comment by DeniseWorthen** [comment] 2024-01-04 13:51
What is the status of this issue?

**Comment by MatthewPyle-NOAA** [comment] 2024-01-04 16:57
> What is the status of this issue?

I think this was addressed within https://github.com/ufs-community/ufs-weather-model/pull/1646, but would be good to get confirmation from @tanyasmirnova and/or @SamuelTrahanNOAA

**Comment by tanyasmirnova** [comment] 2024-01-04 17:14
Yes, I confirm that this was addressed in #1646.

**Comment by DeniseWorthen** [comment] 2024-01-04 17:15
@tanyasmirnova Thanks for confirming. I will close the issue.

**Closed as completed by DeniseWorthen** 2024-01-04 17:15 UTC
Labels: bug
