### ISSUE TITLE
strange zeroes in nsst diurnal variables in first few hours of the forecast

### ISSUE THREAD

**Issue by SamuelTrahanNOAA** [ufs-community/ufs-weather-model#101] opened 2020-04-08 17:11 UTC
The xt variable, and a few others, have invalid data (all zeroes) in the east half of tile 2. The data is corrected by the end of the first diurnal cycle.

**EDIT**: _This problem has existed for several months, so it may be in the operational GFS as well. I have no way to test that._

This is from the current fv3_control regression test:

![fv3-control-xt-sadness](https://user-images.githubusercontent.com/39415369/78812965-4a7f4280-799a-11ea-9818-02ec027f5977.png)

This file contains slightly more than a diurnal cycle from an older version of the FV3 GSD physics regression test, but the fv3_control behaved the same way:

- [gfdl_mp_C96_nsst_xt_discontinuity.pdf](https://github.com/ufs-community/ufs-weather-model/files/4451798/gfdl_mp_C96_nsst_xt_discontinuity.pdf)

**Comment by junwang-noaa** [comment] 2021-03-06 16:10
@SamuelTrahanNOAA Would you please check if the issue is resolved in the latest develop branch? If not, would you please specify which gsd physics regression test has the problem?

**Comment by DeniseWorthen** [comment] 2021-04-23 13:29
I suggest closing this issue; we have not had a response from Sam.

**Closed as completed** 2021-04-23 13:37 UTC

**Comment by SamuelTrahanNOAA** [comment] 2021-04-23 13:53
Sorry, I have been quite busy and this is not in my long tasking list. (I'm on 11 projects.) If it is important for me to test for this bug, let me know and I'll talk to one of my managers next week to put it in my tasking somewhere.

I was told a while ago that this is not a bug, but a side-effect of how the regression test was created. In an actual warm start run, the nsst would be valid since it would have 6 hours in the previous cycle to reach its valid state. The regression test has no initial values for those variables, so they just get filled in with default values. Unfortunately, in FV3, the default value for physics variables is 0 even when that value makes no sense. 

However, nobody counts on the cold start of the GFS to have a useful forecast. In a parallel, the GFS is left to spin up for a few days or a week of warm starts before the first forecast that is analyzed. Hence, in the GFS, this bug is not of any practical importance. It's just an aesthetic issue.

Maybe that's not the case for the regional FV3? Perhaps it is not initializing nsst variables correctly when it processes parent model data?
