### ISSUE TITLE
Update to fms@2023.02.01

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#1874] opened 2023-08-18 03:02 UTC
## Description
The spack-stack dev team is hoping to include the update to the newly released fms@2023.02 in the next spack-stack release (early September). I am wondering if the ufs-weather-model is able to move up.

I built fms@2023.02 in spack-stack with the legacy `fms_io` (i.e. version 1) interface enabled (it's now off by default) on my macOS, and I was able to compile the ufs-weather-model develop as of two days ago with that version loaded. I haven't run any tests though.

## Solution
Please let us know if a move up to fms@2023.02 at some point in September is possible. The ufs-weather-model wouldn't have to move to that version immediately. Only when updating from the spack-stack-1.4.1 modules (plus PIO updates in the chained environment) to 1.5.0 the new FMS version would be used.

## Alternatives
We can also install the existing fms version side by side with the new one to make the process of updating fms in ufs-w-m even easier.

## Related to
See https://github.com/JCSDA/spack-stack/issues/709

**Comment by junwang-noaa** [comment] 2023-08-18 12:07
@climbfuji Thanks for building fms 2023.02 in spack-stack. We hope we can switch to fms2 io when using fms 2023.02 without using -Duse_deprecated_io option. Some updates are required in several components, you can see the [NeedsPort.txt](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/files/12339987/NeedsPort.txt) list and discussion in the fv3 dycore [PR#272](https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/272)

**Comment by climbfuji** [comment] 2023-08-18 12:53
JEDI will need `-Duse_deprecated_io` for some time, thus we have to build it with that option turned on.

**Comment by junwang-noaa** [comment] 2023-08-28 15:18
@Hang-Lei-NOAA would you please make request to install FMS 2023.02 on wcoss2?

**Comment by junwang-noaa** [comment] 2023-09-11 13:55
@climbfuji @natalie-perlin Is there an FMS 2023.02 test version available on hera for people to test it in UFS? Thanks

**Comment by climbfuji** [comment] 2023-09-11 13:56
Yes it will be available as part of spack-stack-1.5.0.

**Comment by junwang-noaa** [comment] 2023-09-11 14:05
@climbfuji Have you tested it in UFS WM? Is it working? I am asking because we need to test it first in order to make request to NCO to install it on wcoss2, which may take some time.

**Comment by climbfuji** [comment] 2023-09-11 14:16
Once, but it needs to be re-tested (by someone else than me). spack-stack-1.5.0 by default uses fms@2023.01, but 2023.02 is available as an alternative.

**Comment by Hang-Lei-NOAA** [comment] 2023-09-11 14:30
@Jun Wang - NOAA Federal ***@***.***> I have prepared to send the
2023.02 to NCO. Since our request to install spack-stack will be delayed.

**Comment by Hang-Lei-NOAA** [comment] 2023-10-04 15:11
Dear all, NCO has installed the fms/2023.02 on wcoss2 cactus and dogwoods
for testing and further will move them to NCO operational structure.
Please test at
module use
/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9
module load fms/2023.02

**Comment by junwang-noaa** [comment] 2023-10-13 14:29
@Hang-Lei-NOAA I tried to compile the fms 2023.02, I got following error:
```
Due to MODULEPATH changes, the following have been reloaded:
  1) netcdf/4.7.4

The following have been reloaded with a version change:
  1) cray-mpich/8.1.9 => cray-mpich/8.1.12     3) hdf5/1.10.6 => hdf5/1.14.0
  2) craype/2.7.8 => craype/2.7.13


Currently Loaded Modules:
  1) craype-x86-rome     (H)   7) nco/4.7.9           13) fms/2023.02
  2) libfabric/1.11.0.0. (H)   8) PrgEnv-intel/8.1.0  14) scotch/7.0.3
  3) craype-network-ofi  (H)   9) intel/19.1.3.304    15) ufs_wcoss2.intel
  4) envvar/1.0               10) craype/2.7.13       16) hdf5/1.14.0
  5) cray-pals/1.2.2          11) cray-mpich/8.1.12   17) netcdf/4.7.4
  6) python/3.8.6             12) cmake/3.20.2
```

As you can see other libraries such as ESMF/MAPL... are not loaded. I think the fms library should be built with cray-mpich/8.1.12 with netcdf 4.9.2. My module file on dogwood at:

/lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231013/ufs-weather-model/modulefiles/ufs_wcoss2.intel.lua

Thanks

**Comment by Hang-Lei-NOAA** [comment] 2023-10-13 14:51
@Jun Wang - NOAA Federal ***@***.***> Do you remember that NCO was
installing the netcdf and hdf5 etc that we are using into:
module load netcdf-A/4.9.2
module load hdf5-A/1.14.0

This module is built with that one.
And there is no preload request in NCO's modulefile.
/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/fms/2023.02.lua

**Comment by Hang-Lei-NOAA** [comment] 2023-10-13 14:59
For all, there is a misunderstanding to be clarified for users.
NCO never used hpc-stack on the operational machines. We just used a
special version of hpc-stack to deliver the code and facilitate the
installation process.
NCO built the libraries under hpc-stack and move them into NCO vertical
structures. We are actually using NCO vertical structures on operational
machines.
This is the same result as that we deliver code to NCO through original
tarballs. e.g. some tarball deliveries are also in NCO vertical structure.
scotch/7.0.3; ecbuild; gftl_shared etc. NCO use their own modulefiles.

**Comment by junwang-noaa** [comment] 2023-10-13 15:00
@Hang-Lei-NOAA can you let me know how to load hdf5-A and netcdf-A? My module file is at:

/lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231013/ufs-weather-model/modulefiles/ufs_wcoss2.intel.lua

Thanks

**Comment by Hang-Lei-NOAA** [comment] 2023-10-13 15:18
@Jun Wang - NOAA Federal ***@***.***> I edit it
into:  /lfs/h2/emc/eib/save/Hang.Lei/ufs_wcoss2.intel.lua

**Comment by junwang-noaa** [comment] 2023-10-13 18:36
@Hang-Lei-NOAA These hdf-A/netcdf-A libraries are not loaded. Here is what I got:
```
Due to MODULEPATH changes, the following have been reloaded:
  1) hdf5/1.10.6     2) netcdf/4.7.4

The following have been reloaded with a version change:
  1) cray-mpich/8.1.9 => cray-mpich/8.1.12     2) craype/2.7.8 => craype/2.7.13


Currently Loaded Modules:
  1) craype-x86-rome     (H)   7) nco/4.7.9           13) fms/2023.02
  2) libfabric/1.11.0.0. (H)   8) PrgEnv-intel/8.1.0  14) scotch/7.0.3
  3) craype-network-ofi  (H)   9) intel/19.1.3.304    15) ufs_wcoss2.intel
  4) envvar/1.0               10) craype/2.7.13       16) hdf5/1.10.6
  5) cray-pals/1.2.2          11) cray-mpich/8.1.12   17) netcdf/4.7.4
  6) python/3.8.6             12) cmake/3.20.2
...
CMake Error at /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ESMF (missing: ESMF_LIBRARY_LOCATION
  ESMF_INTERFACE_LINK_LIBRARIES ESMF_F90COMPILEPATHS) (Required is at least
  version "8.3.0")
Call Stack (most recent call first):
  /apps/spack/cmake/3.20.2/intel/19.1.3.304/utnbptm3hrf7gppztidueu4jogfgemut/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/Modules/FindESMF.cmake:121 (find_package_handle_standard_args)
  CMakeLists.txt:144 (find_package)
```
The error file is at:
/lfs/h2/emc/ptmp/jun.wang/FV3_RT/rt_102039/com*l/err

**Comment by junwang-noaa** [comment] 2023-10-23 14:24
@climbfuji Can we change the issue to "update to fms@2023.02.01" or if you want me to create a separate issue for "updating to fms@2023.02.01? Thanks

**Comment by climbfuji** [comment] 2023-10-23 14:36
> @climbfuji Can we change the issue to "update to fms@2023.02.01" or if you want me to create a separate issue for "updating to fms@2023.02.01? Thanks

@junwang-noaa I changed it.

**Comment by Hang-Lei-NOAA** [comment] 2023-10-24 18:38
@Jun Wang - NOAA Federal ***@***.***> NCO has installed the
fms/2023.02.01 on para, Please test it on dogwoods.Then they will move it
to prod
/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9/fms/2023.02.01.lua
module use
/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9
module load fms/2023.02.01
~> ls /apps/ops/para/libs/intel/19.1.3.304/cray-mpich/8.1.9/fms/2023.02.01
include_r4  include_r8  lib

**Comment by junwang-noaa** [comment] 2023-10-25 02:03
@Hang-Lei-NOAA The compile failed with error:
```
/lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231024/ufs-weather-model/FV3/atmos_cubed_sphere/model/multi_gases.F90(45): error #6580: Name in only-list does not exist or is not acc
essible.   [OPEN_NAMELIST_FILE]
      use fms_mod,           only: check_nml_error, open_namelist_file, close_file
----------------------------------------------------^
/lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231024/ufs-weather-model/FV3/atmos_cubed_sphere/model/multi_gases.F90(45): error #6580: Name in only-list does not exist or is not acc
essible.   [CLOSE_FILE]
      use fms_mod,           only: check_nml_error, open_namelist_file, close_file
------------------------------------------------------------------------^
compilation aborted for /lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231024/ufs-weather-model/FV3/atmos_cubed_sphere/model/multi_gases.F90 (code 1)

```
Did you compile the library with "-Duse_deprecated_io" option? Please see @climbfuji 's comment above.
```
> JEDI will need `-Duse_deprecated_io` for some time, thus we have to build it with that option turned on.
```
I'd suggest you check the fms/2023.02.01 compile options used in spack-stack. Thanks

**Comment by Hang-Lei-NOAA** [comment] 2023-10-25 03:19
@Jun Wang - NOAA Federal ***@***.***> I will coordinate with NCO to
update it with the option. Thanks

**Comment by Hang-Lei-NOAA** [comment] 2023-10-25 16:46
@Jun Wang - NOAA Federal ***@***.***> NCO has updated the
installation of fms/2023.02.01
Please test it as soon as possible. Thanks.

**Comment by junwang-noaa** [comment] 2023-10-26 00:47
@Hang-Lei-NOAA Now the model compiled successfully, but the results show that issue is not fixed. Would you please check if it is fms 2023.02.01 installed, not fms/2023.02? It looks to me it's fms 2023.02. We need the patch in fms/2023.02.01 to fix the problem. Thanks

**Comment by Hang-Lei-NOAA** [comment] 2023-10-26 13:58
@Jun Wang - NOAA Federal ***@***.***> Could you please test my build
on dogwoods before we further check with NCO?
Please also "module show fms/2023.02.01" to make sure that you load the
current lib.

module
use /lfs/h2/emc/eib/save/Hang.Lei/forgdit/install/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9
module load fms/2023.02.01

**Comment by Hang-Lei-NOAA** [comment] 2023-10-26 17:03
@Jun Wang - NOAA Federal ***@***.***> NCO also update their build.
You can directly test the NCO installation. Thanks

**Comment by junwang-noaa** [comment] 2023-10-26 17:15
@Hang-Lei-NOAA I just tested your installation, the results look good. I am testing the NCO's installation now.

**Comment by junwang-noaa** [comment] 2023-10-26 18:21
@Hang-Lei-NOAA The NCO installation still does not work. So I have this in the module file:
```
+prepend_path("MODULEPATH", "/apps/ops/para/libs/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9")
+fms_ver=os.getenv("fms_ver") or "2023.02.01"
+load(pathJoin("fms",fms))
+--prepend_path("MODULEPATH", "/lfs/h2/emc/eib/save/Hang.Lei/forgdit/install/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.9")
+--fms_ver=os.getenv("fms_ver") or "2023.02.01"
+--load(pathJoin("fms",fms))
```
The top one in /apps/ops/para does not work properly, but the bottom one under /lfs/h2/emc/eib/save/Hang.Lei works.

**Comment by Hang-Lei-NOAA** [comment] 2023-10-27 13:41
@Jun Wang - NOAA Federal ***@***.***> Could you please point me to
your test directory? I carefully compared the NCO build log and my build
log yesterday and today. They are the same in settings.  I have to figure
out what NCO made wrong on their end. I hope that it is not something like
the previous impact of default root loading.

**Comment by junwang-noaa** [comment] 2023-10-27 13:55
@Hang-Lei-NOAA My code is on dogwood at:

/lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231024/ufs-weather-model

module file: /lfs/h2/emc/nems/noscrub/jun.wang/ufs-weather/20231024/ufs-weather-model/modulefiles/ufs_wcoss2.intel.lua

You can see the compile log from your installation at:
/lfs/h2/emc/ptmp/jun.wang/FV3_RT/rt_206918/compile_s2swa_32bit_pdlib_intel/out

 from NCO's installation is at:
/lfs/h2/emc/ptmp/jun.wang/FV3_RT/rt_88930/compile_s2swa_32bit_pdlib_intel/out

It looks to me fms/2023.01 is loaded in NCO's installation even though I specified fms 2023.02.01 in the module file. While in your installation, fms/2023.02.01 is loaded. Thanks

**Comment by Hang-Lei-NOAA** [comment] 2023-11-01 19:23
@Jun Wang - NOAA Federal ***@***.***> It is updated. Please resubmit
the job. Thanks

**Comment by junwang-noaa** [comment] 2023-11-02 00:01
@Hang-Lei-NOAA The test runs successfully, the results look good now.

**Comment by junwang-noaa** [comment] 2023-11-06 14:12
@Hang-Lei-NOAA is fms/2023.02.01 installation on wcoss2 finished yet? Would you please let me know the final module directory? Thanks

**Comment by junwang-noaa** [comment] 2023-11-06 14:15
@climbfuji Is it decided that fms 2023.03 will be installed in in spack-stack 1.5.1? Does anyone test the cpld mixed mode test and confirmed the results yet? Thanks

**Comment by climbfuji** [comment] 2023-11-06 14:27
> @climbfuji Is it decided that fms 2023.03 will be installed in in spack-stack 1.5.1? Does anyone test the cpld mixed mode test and confirmed the results yet? Thanks

So far it's only available on Hercules, in addition to 2023.02.1 (which is the default in spack-stack-1.5.1 and available on all platforms):
```
[role-epic@Hercules:/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/envs/unified-env]# find ./ -type d -name 'fms-*'
./install/intel/2022.0.2/fms-2023.02.01-bagqfo6
./install/intel/2022.0.2/fms-release-jcsda-np4324l
./install/intel/2022.0.2/fms-2023.01-7qgjvui
./install/gcc/10.2.0/fms-2023.01-rxbif7m
./install/gcc/10.2.0/fms-release-jcsda-hloh2uu
./install/gcc/10.2.0/fms-2023.02.01-2eesnun
```
We have an issue open for adding 2023.03 on the other platforms: https://github.com/JCSDA/spack-stack/issues/860

As soon as someone from the UFS does the acceptance testing on Hercules and tells us that this version 2023.03 is ok, we will start adding it on the other platforms.

**Comment by junwang-noaa** [comment] 2023-11-06 14:58
Thank you, I will create an issue for testing fms 2023.03 in UFS WM.

**Comment by Hang-Lei-NOAA** [comment] 2023-11-06 15:01
@Jun Wang - NOAA Federal ***@***.***> It is already in the para path
that I previously provide to you on both machines.
To be on prod path, it has to be waiting for the next system maintianence

**Comment by junwang-noaa** [comment] 2023-11-22 15:18
@Hang-Lei-NOAA would you please let us know the location of the following library on wcoss2

fms/2023.02.01
esmf/8.5.0
mapl/2.40.3

Currently we have fms/2023.01, esmf/8.4.2 and mapl/2.35.2 along with other libraries under:

prepend_path("MODULEPATH", "/apps/test/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/modulefiles/compiler/intel/19.1.3.304")
prepend_path("MODULEPATH", "/apps/test/hpc-stack/i-19.1.3.304__m-8.1.12__h-1.14.0__n-4.9.2__p-2.5.10__e-8.4.2/modulefiles/mpi/intel/19.1.3.304/cray-mpich/8.1.12")

Thanks

**Comment by climbfuji** [comment] 2023-11-22 15:19
@junwang-noaa we wanted to go to fms@2023.03 to avoid the gnu issues with 2023.02.01? We just installed fms@2023.03 everywhere (see https://github.com/JCSDA/spack-stack/issues/860)

**Comment by junwang-noaa** [comment] 2023-11-22 15:32
@climbfuji you are correct. My understanding is that right now the fms/2023.02.01(with feature required for GFSv17) is already available in hpc-stack on wcoss2. We did not know the issue with gnu in fms/2023.02.01 on R&D machine when making request to install it on wcoss2. @Hang-Lei-NOAA needs to make a request to install fms@2023.03 on wcoss2, hope that can be installed soon.

**Comment by climbfuji** [comment] 2023-11-22 15:33
Thanks for the clarification! Makes sense.

**Comment by Hang-Lei-NOAA** [comment] 2023-11-22 15:41
@Jun Wang - NOAA Federal ***@***.***>
The fms/2023.02.01 has been in prod. Please check the system installations
on wcoss2.

Bongi is till working on these esmf/8.5.0
On acorn
module load PrgEnv-intel
module load intel
module load craype
module load cray-mpich
module ava
module load esmf-B/8.5.0
module load mapl-B/2.40.3

**Comment by junwang-noaa** [comment] 2023-12-06 20:18
@jkbk2004 @FernandoAndrade-NOAA would you please confirm the fms/2023.02.01 is installed on all the R&D platforms? Thanks

**Comment by climbfuji** [comment] 2023-12-06 20:21
it is in spack-stack-1.5.1, see https://github.com/JCSDA/spack-stack/blob/1.5.1/configs/templates/unified-dev/spack.yaml

**Closed as completed** 2024-01-08 17:03 UTC
Labels: enhancement
