### ISSUE TITLE
Regional restart run is creating different results.

### ISSUE THREAD

**Issue by RatkoVasic-NOAA** [ufs-community/ufs-weather-model#408] opened 2021-02-04 21:37 UTC
## Description
Regional restart regression test is comparing results to itself, and not to control run.
For global application all is OK,

### To Reproduce:
I used regression test to create CONTROL and RESTART work directories and repeated runs using quilting=trrue
phyf*** and dynf*** files differed between the two runs.

## Output

**Screenshots**

**output logs**

```

```

**Comment by junwang-noaa** [comment] 2021-02-17 15:15
@JacobCarley-NOAA May I ask who may work on this issue?

**Comment by jwolff-ncar** [comment] 2021-02-17 15:24
Was this resolved with @DomHeinzeller's commit (#417) or is there still an outstanding issue? (I think this may only be in the release branch at this time.)

**Comment by climbfuji** [comment] 2021-02-17 15:34
> Was this resolved with @DomHeinzeller's commit (#417) or is there still an outstanding issue? (I think this may only be in the release branch at this time.)

This was resolved for the release/public-v2 branch, and the only changes I had to make were (a) code that was added to develop between July 2020 (when the release branch was cut) and December 2020 (from Moorthi and Shan), and (b) NoahMP-specific code changes (these are not yet in develop).

**Comment by junwang-noaa** [comment] 2021-02-18 16:47
@climbfuji I see the restart reproducibility tests in release/public-v2 are for suite files FV3_GFS_v15p2 and FV3_RRFS_v1alpha. While the regional LAM tests are using FV3_GFS_v15_thompson_mynn, and the restart test does not reproduce the control with this suite file. So the release/public-v2 does not support FV3_GFS_v15_thompson_mynn?

**Comment by climbfuji** [comment] 2021-02-18 16:49
It doesn't support it officially, but it will give b4b reproducible results if you add the suite manually and compile it.

**Comment by junwang-noaa** [comment] 2021-02-18 16:57
I tested the latest develop branch, the restart test using FV3_GFS_v15_thompson_mynn do not reproduce from control. Do you mean the release/public-v2 has restart reproducibility for FV3_GFS_v15_thompson_mynn?

**Comment by climbfuji** [comment] 2021-02-18 17:41
> I tested the latest develop branch, the restart test using FV3_GFS_v15_thompson_mynn do not reproduce from control. Do you mean the release/public-v2 has restart reproducibility for FV3_GFS_v15_thompson_mynn?

Yes, 99% confident that it has. But according to Lucas Harris, we shouldn't bring over all these changes 1:1, but fix the regional boundary update script and then remove any unnecessary mpp_update_domain calls in the dycore. I am happy to assist or lead this effort, but not this week.

**Comment by junwang-noaa** [comment] 2022-03-05 00:38
The issue is fixed.

**Closed as completed by junwang-noaa** 2022-03-05 00:38 UTC
Labels: bug
