### ISSUE TITLE
Prototype 7 without wave forecast crash

### ISSUE THREAD

**Issue by bingfu-NOAA** [ufs-community/ufs-weather-model#857] opened 2021-10-06 16:14 UTC
## Description
Provide a clear and concise description of what the bug is.
Also give a description of what behavior you expected to happen.

When running the prototype 7 without wave (i.e. ATM-OCN-ICE) forecast, model has crashes.  

### To Reproduce:
What compilers/machines are you seeing this with?
Give explicit steps to reproduce the behavior.

1. run a 35-day forecast using p7 without wave coupling. 
2. you will get model crash with error info like:
3. It has been tested on Orion and Dell 3.5, crash error info is similar. 

FATAL from PE     0: NetCDF: Numeric conversion not representable
FATAL from PE     0: NetCDF: Numeric conversion not representable
Image              PC                Routine            Line        Source
ufs_model          000000000513EE1A  Unknown               Unknown  Unknown
ufs_model          000000000429ED9B  mpp_mod_mp_mpp_er          68  mpp_util_mpi.inc
ufs_model          00000000041DF532  fms_io_utils_mod_         164  fms_io_utils.F90
ufs_model          000000000421CB39  netcdf_io_mod_mp_         284  netcdf_io.F90
ufs_model          000000000423EDDC  netcdf_io_mod_mp_         373  netcdf_write_data.inc
ufs_model          00000000041F98D4  fms_netcdf_domain         921  domain_write.inc
ufs_model          0000000004565558  diag_output_mod_m        1283  diag_output.F90
ufs_model          000000000413D181  diag_util_mod_mp_        2657  diag_util.F90

**output logs**
/work/noaa/marine/bfu/gfs.forecast.highres.log
```
paste the code here (if a short section of log)
```

**Comment by DeniseWorthen** [comment] 2021-10-06 16:58
This is using the workflow? On what machine? I can't find the directory you point to.

**Comment by pjpegion** [comment] 2021-10-06 16:59
@DeniseWorthen orion

**Comment by bingfu-NOAA** [comment] 2021-10-06 17:01
@DeniseWorthen This is run from workflow, not regression test. The issue happened on both Orion and Dell 3.5
I didn't check other machine.

**Comment by DeniseWorthen** [comment] 2021-10-06 17:02
Thanks, both of you. Where is the run directory?

**Comment by bingfu-NOAA** [comment] 2021-10-06 17:04
@DeniseWorthen 
here is run directory.
/work/noaa/marine/bfu/p7rfcst_c/com/stmp/ctl/2013040100/gfs/fcst.224902

**Comment by bingfu-NOAA** [comment] 2021-10-06 17:09
@jiandewang 
Jiande, can I ask a MOM setting in p7? 
#Set to False for restart reproducibility   
MOM6_REPRO_LA=${MOM6_REPRO_LA:-'True'}
Why is this set to 'True' for p7? 
If I run p7 without wave, should I set it to 'False'
Because I set it to 'False', it looks the run passed the previous crash point.

**Comment by DeniseWorthen** [comment] 2021-10-06 17:12
@bingfu-NOAA The name of that setting changed in the P7 PR:

```
Changes MOM6 setting MOM6_REPRO_LA to MOM6_USE_LI2016. These are equivalent, but the new setting is more descriptive of the setting.
```

There are several namelist changes that need to be propagated to the workflow.

**Comment by bingfu-NOAA** [comment] 2021-10-06 17:20
@DeniseWorthen Is the p7 workflow hash and ufs-weather-model hash correct in this document?https://docs.google.com/document/d/1v7XjK5zThhbxabLM0-Mq1Qg7HoheHAuxJHMHH8bjG2g/edit

**Comment by JessicaMeixner-NOAA** [comment] 2021-10-06 17:23
@bingfu-NOAA the hashes are correct for the workflow and ufs-weather-model used for P7

**Comment by jiandewang** [comment] 2021-10-06 17:25
@bingfu-NOAA hash is the right one, you can double check on HERA
/scratch2/NCEPDEV/climate/role.ufscpara/Prototype7.0/global-workflow
this is what we used for all the P7 runs

**Comment by bingfu-NOAA** [comment] 2021-10-06 17:26
@DeniseWorthen @JessicaMeixner-NOAA I hope someone can do a test to see if the crash can be reproduced, just to make sure if it is not due to my incorrect setting.

**Comment by DeniseWorthen** [comment] 2021-10-06 17:30
I don't run the workflow or have any experience debugging it.

**Comment by jiandewang** [comment] 2021-10-06 17:38
I will take a try on HERA

**Comment by jiandewang** [comment] 2021-10-06 17:39
@bingfu-NOAA where is your code and script on ORION ?

**Comment by bingfu-NOAA** [comment] 2021-10-06 17:41
@jiandewang 
here is the workflow on Orion: /work/noaa/marine/bfu/p7rfcst_c/coupled-workflow
and the rocoto directory: /work/noaa/marine/bfu/p7rfcst_c/ctl
Thanks.

**Comment by DeniseWorthen** [comment] 2021-10-06 20:20
@bingfu-NOAA I ran the cpld_control_c384_p7 RT for 30 hours (so far) and it is running w/o issue. To do this, edit the cpld_control_c384_p7 as shown and then run the single test.

```
diff --git a/tests/tests/cpld_control_c384_p7 b/tests/tests/cpld_control_c384_p7
index a7fc2a05..1b3f99c4 100644
--- a/tests/tests/cpld_control_c384_p7
+++ b/tests/tests/cpld_control_c384_p7
@@ -49,12 +49,20 @@ export LIST_FILES="sfcf006.nc \
 export_fv3
 export_cpl

-export DAYS=0.25
-export FHMAX=6
-export RESTART_N=3
-export RESTART_INTERVAL="${RESTART_N} -1"
-export OUTPUT_FH="3 -1"
-export FHZERO=3
+export SYEAR=2013
+export SMONTH=04
+export SDAY=01
+export SHOUR=00
+export SECS=`expr $SHOUR \* 3600`
+export BMIC=.true.
+
+export DAYS=35
+export FHMAX=840
+export WLCLK=480
+#export RESTART_N=3
+#export RESTART_INTERVAL="${RESTART_N} -1"
+#export OUTPUT_FH="3 -1"
+#export FHZERO=3

 export TASKS=$TASKS_cpl_c384
 export TPN=$TPN_cpl_c384
@@ -107,6 +115,7 @@ export CICEMASK=kmtu_cice_NEMS_mx${OCNRES}.nc
 export CHLCLIM=seawifs-clim-1997-2010.${NX_GLB}x${NY_GLB}.v20180328.nc
 export FRUNOFF=runoff.daitren.clim.${NX_GLB}x${NY_GLB}.v20180328.nc
 export MOM6_RIVER_RUNOFF=True
+export MOM6_RESTART_SETTING=r

 export FNALBC="'C384.snowfree_albedo.tileX.nc'"
 export FNALBC2="'C384.facsf.tileX.nc'"
```

My run directory on hera is ``` /scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_6741/cpld_control_c384_p7```

**Comment by jiandewang** [comment] 2021-10-06 20:34
I compared the MOM_input between Denise run /scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_6741/cpld_control_c384_p7
and Bing Fu run /work/noaa/marine/bfu/p7rfcst_c/com/stmp/ctl/2013040100/gfs/fcst.296920/INPUT

the only difference is
< USE_LA_LI2016 = False   <-- Denise
---
> USE_LA_LI2016 = True   <-- Bing

so workflow w/o wave should work with F.

**Comment by bingfu-NOAA** [comment] 2021-10-06 20:43
@jiandewang 
USE_LA_LI2016 is also True from denise's run. 
I am looking at the run directory to see if there is something else.

**Comment by jiandewang** [comment] 2021-10-06 20:52
> @jiandewang USE_LA_LI2016 is also True from denise's run. I am looking at the run directory to see if there is something else.

Bing, you are right, it is T in Denise's run but F in your runs at
/work/noaa/marine/bfu/p7rfcst_c/com/stmp/ctl/2013040100/gfs/fcst.296920/INPUT

**Comment by bingfu-NOAA** [comment] 2021-10-06 21:47
@DeniseWorthen I can't find any suspicious difference between your run and my run. I will move to Hera and use same layout (6x8) to run a test, so that it is easier to compare.  My run on Orion/Dell with 12x12 layout both failed.

**Comment by jiandewang** [comment] 2021-10-07 01:16
I know the reason now: some wave related variables are listed in diag_table but here wave is off.
@bingfu-NOAA you may see my test run on Orion at 
/work/noaa/marine/Jiande.Wang/working/P7-nowave/WORK/DATA/R20130401/2013040100/gfs/fcst.413665
it has finished 6hr already, see diag_table in the above directory, line 86-101

**Comment by jiandewang** [comment] 2021-10-07 01:32
my 24hr test run have finished without issue.

**Comment by bingfu-NOAA** [comment] 2021-10-07 01:36
@jiandewang That is a good point. I will revise the diag_table on Dell and submit a test.

**Comment by DeniseWorthen** [comment] 2021-10-07 11:59
@bingfu-NOAA Once you've confirmed that the diag_table is the problem, would you remember to close this issue?

**Comment by bingfu-NOAA** [comment] 2021-10-07 19:09
@DeniseWorthen @jiandewang @pjpegion My run with revised diag_table (remove wave-ocn variables) is successful, I am going to close the issue right now, thank you all for helping me solve the issue.

**Closed as completed** 2021-10-07 19:10 UTC
Labels: bug
