### ISSUE TITLE
Enable write grid component outputting both parent and nested domains

### ISSUE THREAD

**Issue by BinLiu-NOAA** [ufs-community/ufs-weather-model#555] opened 2021-05-03 21:46 UTC
## Description
Currently, in ufs-weather-model, existing write grid component capabilities include:
- Asynchronous IO with dedicated IO groups (nodes/PEs)
- Support regular, compressed, and parallel netcdf format output
- Conduct inline post

And supported output grid options include:
- For global domain:
  - Gaussian grid netcdf format (gaussian_grid)
  - Global regular lat-lon grid (global_latlon)
- For regional or nested domains:
  - Regular lat-lon grid in netcdf format (regional_latlon)
  - Rotated lat-lon grid in netcdf format (rotated_latlon)
  - Lambert conformal grid in netcdf format (lambert_conformal)
- Native model grid in netcdf format for both global and regional/nested domains (cubed_sphere_grid)

And the supported UFS model domain configurations are:
- Global domain with 6 tiles (uniform, stretched)
- Regional domain with regular gnomonic grid or Extended Schmidt Gnomonic (ESG) grid (the single 7th tile)
- Global domain (6 tiles) with one nested domain (tile# 7), which currently can only output either the global domain or nested domain, but not both

Discussions among EMC EIB and hurricane project team have initiated developments to expand the write grid component so that it will also be able to deal with various global-nesting and regional-nesting configurations, e.g.
- Enable outputting both the global/parent domain and nested domains when choosing other output grid options than cubed_sphere_grid
- Support global domain (6 tiles) with multiple static and telescopic nested domains
- Support global domain (6 tiles) with storm-following or prescribed moving nested domains
- Support regional parent domain with multiple static and telescopic nested domains
- Support regional parent domain with storm-following or prescribed moving nested domains

Note: The global moving nesting capability and regional nesting (moving-nesting) capability are still under active developments (not yet available).

**Comment by junwang-noaa** [comment] 2021-05-04 15:31
Bin, I made code changes in my branches created from the latest ufs-weather-model/fv3atm develop branches. would you please provide a test case C96 global (6 tiles) with 1 nest using the ufs-weather-model develop branch?

**Comment by BinLiu-NOAA** [comment] 2021-05-04 16:10
Thanks, @junwang-noaa!

I went through the existing regression tests in ufs-weather-model develop, and we can use this existing RT of fv3_stretched_nest for the global with 1 static nest configuration as a start point. It was configured to write out the output on the native model grid in netcdf format for both global and nested domains/tiles (cubed_sphere_grid) currently. And I conducted this test with the latest ufs-weather-model develop branch here on Orion:
/work/noaa/stmp/bliu/stmp/bliu/FV3_RT/rt_56555/fv3_stretched_nest

This would serve as a very good start point for developing and testing other output grid options (regular latlon, rotated laton, etc.) for both global and nested domains, if we currently focus on the global with one static nest configuration. For the multiple nesting configurations, I can set up example tests later on.

Please feel free to let me know if you have any suggestions/comments.

Thanks!

Bin

**Comment by junwang-noaa** [comment] 2022-02-14 15:26
This issue is going to be resolved in PR #1044. 

Please create an new issue for moving nest capability.

**Comment by BinLiu-NOAA** [comment] 2022-02-16 20:00
@junwang-noaa, I have just created a new issue #1053 for moving nest write grid component support. Thanks!

**Comment by junwang-noaa** [comment] 2022-02-24 16:34
The PR #1044 was merged, the issue is closed.

**Closed as completed by junwang-noaa** 2022-02-24 16:34 UTC
Labels: enhancement
