### ISSUE TITLE
hafs_regional_atm_ocn_wav seems to have incorrect global wind fields at startup

### ISSUE THREAD

**Issue by DeniseWorthen** [ufs-community/ufs-weather-model#993] opened 2022-01-04 19:28 UTC
## Description

In this test, the ATM and WAV domains do not completely overlap. Wind fields from a file are used to fill values in the areas of WAV domain which are outside of the ATM domain. In addition, at startup, the import fields from ATM are zero everywhere so that the values from the files are needed everywhere at the first model Advance. 

Running this test from the develop branch and adding the following change in wmesmf.F90:
```
@@ -2593,6 +2597,14 @@
 #ifdef W3_WRST
        endif  !if ( twn-tw0 .le. 0  )
 #endif
+        write(msgString,'(A,6g14.7)')'X wx0  ', wx0(782:787,50)
+        call ESMF_LogWrite(trim(msgString), ESMF_LOGMSG_INFO)
+        write(msgString,'(A,6g14.7)')'X wxn  ', wxn(782:787,50)
+        call ESMF_LogWrite(trim(msgString), ESMF_LOGMSG_INFO)
+        write(msgString,'(A,6g14.7)')'X wy0  ', wy0(782:787,50)
+        call ESMF_LogWrite(trim(msgString), ESMF_LOGMSG_INFO)
+        write(msgString,'(A,6g14.7)')'X wyn  ', wyn(782:787,50)
+        call ESMF_LogWrite(trim(msgString), ESMF_LOGMSG_INFO)
       endif
 !
 ! -------------------------------------------------------------------- /
@@ -2636,13 +2648,13 @@
 ! -------------------------------------------------------------------- /
 ! Post
 !
```

will write the global wind fields along j=50. At this j-row,  the domain boundary occurs at i=785 so values at i>=785 will be coming from the file but i-values less than that are coming from the import field.
 
At the first model advance, the following is written (the PET # does not matter since these are global fields on all PEs):

```
20220104 121200.104 INFO             PET400    Exit BlendImpField
20220104 121200.116 INFO             PET400   X wx0    0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
20220104 121200.116 INFO             PET400   X wxn    0.000000      0.000000      0.000000      3.420168      3.444951      3.432225
20220104 121200.116 INFO             PET400   X wy0    0.000000      0.000000      0.000000      0.000000      0.000000      0.000000
20220104 121200.116 INFO             PET400   X wyn    0.000000      0.000000      0.000000      6.126642      6.116197      6.027511
20220104 121200.171 INFO             PET400   WAV: leaving GetImport
```
Since the import fields are all zero at the first advance, all values at this model advance should be coming from the file and be non-zero.

**Comment by JessicaMeixner-NOAA** [comment] 2022-01-04 19:33
I think the values of the wind should only be non-zero if you have a restart file (for mediator or WW3), but maybe @uturuncoglu or @BinLiu-NOAA remembers better than I do.

**Comment by uturuncoglu** [comment] 2022-01-04 20:05
@JessicaMeixner-NOAA @DeniseWorthen As a part of the HAFS project we never tested restart capability. That was out of our scope in that time. So, there might me still issue over there.

**Comment by DeniseWorthen** [comment] 2022-01-04 20:18
Thanks @uturuncoglu. This is not a restart test; this is simply running the RT from the develop branch where we have non-overlapping domains for the ATM and WAV. The values from the file are used to fill the part of the WAV domain which lies outside of the ATM domain.

I thought I understood how the filling of the values from the file is supposed to work. The 10m winds in the import state are initially zero so you use the values from the file everywhere. After the 10m winds in the import state become valid, you use those winds everywhere, except for the region of WAV which does not overlap the ATM. But what I'm seeing is that at that first Advance, when the values should be non-zero everywhere since they're coming from the file, they're still zero.

**Comment by uturuncoglu** [comment] 2022-01-05 05:26
@DeniseWorthen you mean it is zero over the active coupling region or everywhere. If it is zero over active coupling region only then the cap needs to handle it specially for the initial time step. As I know the current implementation only blends data (zero or not) and does not account it is first advance or not.

**Comment by DeniseWorthen** [comment] 2022-01-05 13:44
@uturuncoglu It appears to be zero over the active coupling region. I'm not sure I understand your comment about masking doesn't account for being first advance or not? (https://github.com/NOAA-EMC/WW3/blob/46b3896ecac921f24335c8f1ef81daaaf4287b1b/model/src/wmesmfmd.F90#L2530). 

I found this issue when comparing what I had implemented for HAFS in the new cap, because I had put in what I think is the correct logic for when and where to use the data from the file.

Comparing the old and new caps using the mediator history file, at the first export the roughness length is equal (and very small, O~10-13) for both the old cap and new cap. But if I look at the second and third exports, what I see is that the old cap apparently has no forcing in the active coupling region, only in the data region. This plot shows j=50 across the domain, where i=785 is the boundary between active and data. The upper plot is the 2nd export (t=12min) and the bottom plot is the 3rd export (t=18min)

<img width="676" alt="Screen Shot 2022-01-05 at 8 29 59 AM" src="https://user-images.githubusercontent.com/40498404/148226637-0cf3f5e5-e310-44f2-aa8c-18b033e35e0d.png">

At the end of the test (6 hours), the fields are nearly the same, but I think there is a problem w/ how the existing cap is doing the initial filling.

**Comment by JessicaMeixner-NOAA** [comment] 2022-01-05 13:46
The wmesmf cap has a special switch WRST which takes values from the WW3 restart file -- if you are using that switch and have no restart file, the first time step will be zero.  We do not use restart files in the regression tests, but in other runs we do.

**Comment by DeniseWorthen** [comment] 2022-01-05 14:22
At the time of export from the second model advance (t=12, the upper plot), the WAV model should have valid non-zero fields from the ATM in the active coupling region because the ATM has actually run at that point. The issue I believe lies in how and when the import mask is given valid values. 

It seems clear to me that the import mask in the old cap is not correct until the third model advance. At the second model advance, you're not using the part of the domain which should have valid import winds from the ATM---that is why the export of roughness length is essentially unchanged in the active coupling region (i<785) but has reasonable values in the part of the domain where the values are coming from the forcing file. By the time of the third advance the import mask is finally correct and you have valid wind values everywhere.

**Comment by DeniseWorthen** [comment] 2022-02-02 14:58
For completeness, these are the exported Sw_z0 fields at the first and second ModelAdvance when the run sequence is fixed as in PR #1034 

![wavImp_Sw_z0_2019-08-29-00360](https://user-images.githubusercontent.com/40498404/152178408-f5e24c76-cf24-4aac-9cec-4957c6d97fe7.jpg)
![wavImp_Sw_z0_2019-08-29-00720](https://user-images.githubusercontent.com/40498404/152178427-77cbb6a0-7e9e-431f-87ee-c6571e95dccf.jpg)

**Comment by junwang-noaa** [comment] 2022-02-03 18:21
@DeniseWorthen So the problem is fixed, can you close the issue?

**Comment by DeniseWorthen** [comment] 2022-02-03 19:39
No, the issue won't be fixed until I bring in the new cap for HAFS.

**Closed as completed** 2022-05-31 16:16 UTC
Labels: bug
