### ISSUE TITLE
Runtime files in the wrong directory in Regression tests.

### ISSUE THREAD

**Issue by aerorahul** [ufs-community/ufs-weather-model#487] opened 2021-03-26 20:58 UTC
## Description
Inspecting the runtime directory of a test e.g. `fv3_control`, the `INPUT` directory is containing files it should not contain.

Here is a listing of `fv3_control/INPUT`

```
ls fv3_control/INPUT
aerosol.dat                 co2historicaldata_1981.txt  co2historicaldata_2013.txt
C96_grid.tile1.nc           co2historicaldata_1982.txt  co2historicaldata_2014.txt
C96_grid.tile2.nc           co2historicaldata_1983.txt  co2historicaldata_2015.txt
C96_grid.tile3.nc           co2historicaldata_1984.txt  co2historicaldata_2016.txt
C96_grid.tile4.nc           co2historicaldata_1985.txt  co2historicaldata_glob.txt
C96_grid.tile5.nc           co2historicaldata_1986.txt  co2monthlycyc.txt
C96_grid.tile6.nc           co2historicaldata_1987.txt  fv3_increment.nc
co2historicaldata_1956.txt  co2historicaldata_1988.txt  gfs_ctrl.nc
co2historicaldata_1957.txt  co2historicaldata_1989.txt  gfs_data.tile1.nc
co2historicaldata_1958.txt  co2historicaldata_1990.txt  gfs_data.tile2.nc
co2historicaldata_1959.txt  co2historicaldata_1991.txt  gfs_data.tile3.nc
co2historicaldata_1960.txt  co2historicaldata_1992.txt  gfs_data.tile4.nc
co2historicaldata_1961.txt  co2historicaldata_1993.txt  gfs_data.tile5.nc
co2historicaldata_1962.txt  co2historicaldata_1994.txt  gfs_data.tile6.nc
co2historicaldata_1963.txt  co2historicaldata_1995.txt  global_o3prdlos.f77
co2historicaldata_1964.txt  co2historicaldata_1996.txt  grid_spec.nc
co2historicaldata_1965.txt  co2historicaldata_1997.txt  oro_data.tile1.nc
co2historicaldata_1966.txt  co2historicaldata_1998.txt  oro_data.tile2.nc
co2historicaldata_1967.txt  co2historicaldata_1999.txt  oro_data.tile3.nc
co2historicaldata_1968.txt  co2historicaldata_2000.txt  oro_data.tile4.nc
co2historicaldata_1969.txt  co2historicaldata_2001.txt  oro_data.tile5.nc
co2historicaldata_1970.txt  co2historicaldata_2002.txt  oro_data.tile6.nc
co2historicaldata_1971.txt  co2historicaldata_2003.txt  sfc_ctrl.nc
co2historicaldata_1972.txt  co2historicaldata_2004.txt  sfc_data.tile1.nc
co2historicaldata_1973.txt  co2historicaldata_2005.txt  sfc_data.tile2.nc
co2historicaldata_1974.txt  co2historicaldata_2006.txt  sfc_data.tile3.nc
co2historicaldata_1975.txt  co2historicaldata_2007.txt  sfc_data.tile4.nc
co2historicaldata_1976.txt  co2historicaldata_2008.txt  sfc_data.tile5.nc
co2historicaldata_1977.txt  co2historicaldata_2009.txt  sfc_data.tile6.nc
co2historicaldata_1978.txt  co2historicaldata_2010.txt  sfc_emissivity_idx.txt
co2historicaldata_1979.txt  co2historicaldata_2011.txt  solarconstant_noaa_an.txt
co2historicaldata_1980.txt  co2historicaldata_2012.txt
```

### To Reproduce:
What compilers/machines are you seeing this with?
Run `rt.sh -k` to keep the run directory. Do so for a single test e.g. `fv3_control`
cd into the run directory and inspect.

<img width="1042" alt="Screen Shot 2021-03-26 at 4 57 19 PM" src="https://user-images.githubusercontent.com/11394126/112691874-56d30880-8e54-11eb-9326-6c7a72f3158e.png">

## Output

**Screenshots**
See attached screen shot

This is because (at least on Orion), the `INPUT` directory in the `INPUTDATA_ROOT` contains these files, and it shouldn't.
Here is a listing (on Orion) of `/work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20210212/FV3_input_data/INPUT`
```
510 Orion-login-2 ~ ❯❯❯ ls /work/noaa/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20210212/FV3_input_data/INPUT
aerosol.dat                 co2historicaldata_1981.txt  co2historicaldata_2013.txt
C96_grid.tile1.nc           co2historicaldata_1982.txt  co2historicaldata_2014.txt
C96_grid.tile2.nc           co2historicaldata_1983.txt  co2historicaldata_2015.txt
C96_grid.tile3.nc           co2historicaldata_1984.txt  co2historicaldata_2016.txt
C96_grid.tile4.nc           co2historicaldata_1985.txt  co2historicaldata_glob.txt
C96_grid.tile5.nc           co2historicaldata_1986.txt  co2monthlycyc.txt
C96_grid.tile6.nc           co2historicaldata_1987.txt  fv3_increment.nc
co2historicaldata_1956.txt  co2historicaldata_1988.txt  gfs_ctrl.nc
co2historicaldata_1957.txt  co2historicaldata_1989.txt  gfs_data.tile1.nc
co2historicaldata_1958.txt  co2historicaldata_1990.txt  gfs_data.tile2.nc
co2historicaldata_1959.txt  co2historicaldata_1991.txt  gfs_data.tile3.nc
co2historicaldata_1960.txt  co2historicaldata_1992.txt  gfs_data.tile4.nc
co2historicaldata_1961.txt  co2historicaldata_1993.txt  gfs_data.tile5.nc
co2historicaldata_1962.txt  co2historicaldata_1994.txt  gfs_data.tile6.nc
co2historicaldata_1963.txt  co2historicaldata_1995.txt  global_o3prdlos.f77
co2historicaldata_1964.txt  co2historicaldata_1996.txt  grid_spec.nc
co2historicaldata_1965.txt  co2historicaldata_1997.txt  oro_data.tile1.nc
co2historicaldata_1966.txt  co2historicaldata_1998.txt  oro_data.tile2.nc
co2historicaldata_1967.txt  co2historicaldata_1999.txt  oro_data.tile3.nc
co2historicaldata_1968.txt  co2historicaldata_2000.txt  oro_data.tile4.nc
co2historicaldata_1969.txt  co2historicaldata_2001.txt  oro_data.tile5.nc
co2historicaldata_1970.txt  co2historicaldata_2002.txt  oro_data.tile6.nc
co2historicaldata_1971.txt  co2historicaldata_2003.txt  sfc_ctrl.nc
co2historicaldata_1972.txt  co2historicaldata_2004.txt  sfc_data.tile1.nc
co2historicaldata_1973.txt  co2historicaldata_2005.txt  sfc_data.tile2.nc
co2historicaldata_1974.txt  co2historicaldata_2006.txt  sfc_data.tile3.nc
co2historicaldata_1975.txt  co2historicaldata_2007.txt  sfc_data.tile4.nc
co2historicaldata_1976.txt  co2historicaldata_2008.txt  sfc_data.tile5.nc
co2historicaldata_1977.txt  co2historicaldata_2009.txt  sfc_data.tile6.nc
co2historicaldata_1978.txt  co2historicaldata_2010.txt  sfc_emissivity_idx.txt
co2historicaldata_1979.txt  co2historicaldata_2011.txt  solarconstant_noaa_an.txt
co2historicaldata_1980.txt  co2historicaldata_2012.txt
```

It is possible that other `INPUT` directories also contain unnecessary files.

**Comment by junwang-noaa** [comment] 2021-06-21 02:56
The issue is fixed in #561, close issue.

**Closed as completed by junwang-noaa** 2021-06-21 02:56 UTC
Labels: bug
