### ISSUE TITLE
Upgrade upp lib to 10.0.10

### ISSUE THREAD

**Issue by WenMeng-NOAA** [ufs-community/ufs-weather-model#840] opened 2021-09-29 15:16 UTC
## Description
The UPP has new release to support GFS, RRFS and HAFS development. The main updates include:

- Add SSMISF17 generation for HAFS.
- Fix for PVU issue from GFS V16 for GFSV17.
- Add new land related fields for GFS V17.
- Hot fix for 1000 mb HGT corrupted at RRFS 3km parallel run.

## Solution
Update upp lib to 10.0.10.

## Alternatives
If applicable, add a description of any alternative solutions or features you've considered.

## Related to
Directly reference any issues or PRs in this or other repositories that this is related to, and describe how they are related. Example:
- required to support noaa-emc/nems/issues/<issue_number>
- needed by noaa-emc/fv3atm/pull/<pr_number>

**Comment by junwang-noaa** [comment] 2021-10-07 12:05
@WeiguoWang-NOAA will this update change ufs-weather-model results?

**Comment by WenMeng-NOAA** [comment] 2021-10-26 13:07
The changes in PR #841 were combined in PR #714 to merge in develop branch.

**Comment by junwang-noaa** [comment] 2021-10-28 16:08
The code updates were committed, the issue is closed.

**Closed as completed by junwang-noaa** 2021-10-28 16:08 UTC
Labels: enhancement
