### ISSUE TITLE
Add support for Stochastically Perturbed Parameterizations (SPP) in the FV3

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/ufs-weather-model#978] opened 2021-12-24 23:34 UTC
## Description
Add the necessary code in ufs-weather-model, fv3atm, ccpp-physics, and stochastic_physics to run the FV3 with Stochastically Perturbed Parameterizations (SPP).  The associated code uses the stochastic_physics pattern generator (same as for SKEB, SHUM, and SPPT) to create a random pattern based on scales, magnitudes, etc., from the FV3 input.nml namelist and perturbs RAP/HRRR-based physics scheme parameters in selected parameterizations.

Namelist options:
&gfs_physics_nml
do_spp = .true. or .false.  -- flag to turn SPP on/off; .false. is the default
n_var_spp = 1 -- determines the number of RAP/HRRR-based schemes that will be perturbed by SPP (these include MYNN SFC, MYNN PBL, RRTMG, GSL GWD, and Thompson MP)

&nam_spperts (new stanza in namelist; all settings here are comma separated and apply to the parameterizations listed in 'spp_var_list')
iseed_spp = 4 -- the initial seed value for the pattern
spp_lscale = 150000.0 -- length scale
spp_prt_list = 0.2 -- perturbation magnitude
spp_sigtop1 = 0.1 -- controls vertical tapering of perturbations at the tropopause
spp_sigtop2 = 0.025 -- controls vertical tapering of perturbations at the tropopause
spp_stddev_cutoff = 2.0 -- perturbation magnitude cutoff in number of standard deviations from the mean
spp_tau = 21600.0 -- time decorrelation length
spp_var_list = 'gwd' -- the list of parameterizations to perturb (options include 'pbl', 'sfc', 'rad', 'gwd', and 'mp')
 
## Solution
Perturbs selected parameters in RAP/HRRR-based physics parameterizations, identically to how SPP was implemented in WRF ([Jankov et al 2017](https://journals.ametsoc.org/view/journals/mwre/145/4/mwr-d-16-0160.1.xml) and [Jankov et al 2019](https://journals.ametsoc.org/view/journals/mwre/147/1/mwr-d-18-0092.1.xml)).  Uses pre-existing SPP code in ccpp-physics from WRF-based parameterizations, but which was disabled during the transition to CCPP.  Changes were only made where necessary to implement all parameter perturbations correctly within CCPP.

## Related to
PR #982 and needed by companion PRs in [stochastic_physics](https://github.com/noaa-psd/stochastic_physics/pull/51), [ccpp-physics](https://github.com/NCAR/ccpp-physics/pull/820), and [fv3atm](https://github.com/NOAA-EMC/fv3atm/pull/454).

@llpcarson, @jwolff-ncar, @willmayfield, @bluefinweiwei, @michelleharrold, @judithberner, @pjpegion

**Comment by junwang-noaa** [comment] 2022-03-05 00:27
The code changes were committed, The issue is closed.

**Closed by junwang-noaa** 2022-03-05 00:27 UTC
Labels: enhancement
