### ISSUE TITLE
Complete feature tests for RAP physics

### ISSUE THREAD

**Issue by climbfuji** [ufs-community/ufs-weather-model#953] opened 2021-12-12 21:08 UTC
## Description

PR https://github.com/ufs-community/ufs-weather-model/pull/937 adds several regression tests based on the RAP physics, including feature tests (restart, decomp, 2threads, ...). The following test fails with the RAP suite + GFS SFCDIFF:
```
rap_sfcdiff_decomp
```
The following tests fail with the RAP suite (default MYNN SFC):
```
rap_restart
rap_decomp
```
It seems like that the decomp issue is unrelated to the surface layer scheme, therefore fixing it for one of the tests will likely fix it for the other, too. Once the restart issue for the RAP (MYNN SFC) test is fixed, all RAP SFCDIFF feature tests can be removed (except for `rap_sfcdiff_debug`).

Also, when #937 was merged, the 2thread tests `rap_2threads` were turned off on `jet.intel` and `wcoss_cray` (because of wrong task geometry settings I think). They ran fine on all other platforms. It should be checked if they can be turned on with the correct settings (tasks per node etc.).

**Comment by arunchawla-NOAA** [comment] 2022-03-09 23:37
there were a number of PRs merged related to this issue. @climbfuji is this still a problem ?

**Comment by climbfuji** [comment] 2022-03-10 00:38
@arunchawla-NOAA Yes, there is still a problem with b4b reproducibility when changing the MPI decomposition.

**Comment by climbfuji** [comment] 2022-05-25 03:31
@junwang-noaa @SamuelTrahanNOAA @grantfirl I started working on this. The decomp differences are definitely coming from the Grell Freitas scheme. When I return immediately from that scheme (after setting `errmsg` and `errflg`), differences are zero after two time steps. If I run GF, results are different after two time steps when changing the MPI decomposition. Stay tuned.

**Comment by climbfuji** [comment] 2022-06-06 02:26
The remaining RAP (GF) decomp b4b issue is fixed in https://github.com/ufs-community/ufs-weather-model/pull/1243 and associated PRs for fv3atm and ccpp-physics :-)

**Comment by SamuelTrahanNOAA** [comment] 2022-06-07 15:32
This should be combined with #1257 which enables the full feature set for hrrr_control. Fortunately, that one needs no code changes.

**Comment by SamuelTrahanNOAA** [comment] 2022-06-10 20:13
I've merged Dom's fix for this issue with my PR here:

https://github.com/ufs-community/ufs-weather-model/pull/1257

**Comment by SamuelTrahanNOAA** [comment] 2022-06-17 14:53
@climbfuji Your bugfix has been merged. Can you confirm the issue is resolved, and close it if it is?

**Closed as completed** 2022-06-17 15:18 UTC
Labels: bug
