### ISSUE TITLE
P7c debug (without waves) error

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#758] opened 2021-08-20 13:23 UTC
## Description

The p7c set-up without waves segfaulted when run in debug mode. 

### To Reproduce:

This test was run via the global-workflow from the feature/coupled-crow branch.  "-DDEBUG=ON" was added to the build for the ufs-weather-model and then a prototype7nowaves case file was made from the prototype7 case file.    I can either provide a branch where these changes are checked in, or if preferred I could provide a canned case.  I did forget to change the run-time modules to the debug modules, but they should have been built with the debug modules. 

## Output

Log file: 
/scratch2/NCEPDEV/climate/Jessica.Meixner/p7update/debug-test01/COM/debug01/logs/2013040100/gfs.forecast.highres.log
The error: 
```
srun: error: h33m38: task 1152: Segmentation fault (core dumped)
srun: launch/slurm: _step_signal: Terminating StepId=21743413.0
slurmstepd: error: *** STEP 21743413.0 ON h4c03 CANCELLED AT 2021-08-19T13:07:37 ***
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
ufs_model          000000000C8B5B2E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002AC3DF0B4630  Unknown               Unknown  Unknown
ufs_model          0000000007617A40  Unknown               Unknown  Unknown
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source
ufs_model          000000000C8B5B2E  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B5EC095C630  Unknown               Unknown  Unknown
ufs_model          0000000006BE0AA6  cires_ugwpv1_solv         587  cires_ugwpv1_solv2.F90
ufs_model          0000000006A4D033  ugwpv1_gsldrag_mp         675  ugwpv1_gsldrag.F90
ufs_model          000000000537CD8B  oupled_nsstnoahmp        1283  ccpp_FV3_GFS_v16_coupled_nsstNoahmpUGWPv1_physics_cap.F90
ufs_model          0000000005022BBB  ccpp_static_api_m         731  ccpp_static_api.F90
ufs_model          0000000005013A7C  ccpp_driver_mp_cc         188  CCPP_driver.F90
libiomp5.so        00002B5EBED64A43  __kmp_invoke_micr     Unknown  Unknown
libiomp5.so        00002B5EBED27CDA  Unknown               Unknown  Unknown
libiomp5.so        00002B5EBED295B6  __kmp_fork_call       Unknown  Unknown
libiomp5.so        00002B5EBECE7BB0  __kmpc_fork_call      Unknown  Unknown
ufs_model          0000000005011752  ccpp_driver_mp_cc         169  CCPP_driver.F90
ufs_model          000000000252B405  atmos_model_mod_m         346  atmos_model.F90
ufs_model          0000000001EE518A  module_fcst_grid_         787  module_fcst_grid_comp.F90
ufs_model          00000000009806CE  _ZN5ESMCI6FTable1        2036  ESMCI_FTable.C
ufs_model          0000000000984316  ESMCI_FTableCallE         765  ESMCI_FTable.C
ufs_model          000000000076874A  _ZN5ESMCI2VM5ente        1211  ESMCI_VM.C
ufs_model          0000000000981D67  c_esmc_ftablecall         922  ESMCI_FTable.C
ufs_model          00000000007F0B51  esmf_compmod_mp_e        1214  ESMF_Comp.F90
ufs_model          0000000000B73F74  esmf_gridcompmod_        1889  ESMF_GridComp.F90
ufs_model          0000000001EC23BF  fv3gfs_cap_mod_mp        1023  fv3_cap.F90
ufs_model          0000000001EC04DC  fv3gfs_cap_mod_mp         920  fv3_cap.F90
```

**Comment by DeniseWorthen** [comment] 2021-08-20 19:14
I am not able to reproduce this error in the cpld_debug_p7 test in this [branch](https://github.com/DeniseWorthen/ufs-weather-model/tree/feature/cpld_v16bs2). A run directory is here:

``/scratch1/NCEPDEV/stmp2/Denise.Worthen/FV3_RT/rt_15132/cpld_debug_p7``

**Comment by DeniseWorthen** [comment] 2021-08-20 20:55
I repeated the debug test in a c384 sandbox (copying in the executable from the cpld_debug) and it also ran until it timed out.

**Comment by JessicaMeixner-NOAA** [comment] 2021-08-20 20:57
Thanks @DeniseWorthen I must have done something wrong in my test. Should we go ahead and close this issue?

**Comment by DeniseWorthen** [comment] 2021-08-20 21:04
Is your failure repeatable? Do you have a run directory where you could copy the debug executable I built or does the workflow not allow that sort of testing?

**Comment by JessicaMeixner-NOAA** [comment] 2021-08-25 13:31
@DeniseWorthen apologies for the delay, I was able to repeat my original failed tests. 

To repeat: 
cp -r  /scratch2/NCEPDEV/climate/Jessica.Meixner/p7debugcannedcase/CannedCaseInput yourrundir 
cd yourrundir 
sbatch job_card 

I have two test outputs from this: 
1. using the original set of modules:  /scratch2/NCEPDEV/climate/Jessica.Meixner/p7debugcannedcase/testdebug01
2. using debug modules: /scratch2/NCEPDEV/climate/Jessica.Meixner/p7debugcannedcase/testdebug02 

The executable in the run directory compiled the code in: /scratch2/NCEPDEV/climate/Jessica.Meixner/p7update/debug-workflow/sorc/ufs_coupled.fd using the build script: /scratch2/NCEPDEV/climate/Jessica.Meixner/p7update/debug-workflow/sorc/build_ufs_coupled.sh

**Comment by junwang-noaa** [comment] 2021-09-13 12:23
@JessicaMeixner-NOAA Would you please confirm this is an issue with the cpld_control_c384_p7 in [PR#765](https://github.com/ufs-community/ufs-weather-model/pull/765) which uses the regression test script to compile and run the code. Thanks

**Comment by JessicaMeixner-NOAA** [comment] 2021-09-13 18:36
My runs keep failing due to wall clock and can run 1 hour  in debug without failing. The failure I originally had happened fairly quickly, so looks like recent code changes have solved this issue. Let me know if you'd like me to increase the wall clock time again and try again.  The only modification I made (beyond increasing wall clock) was to run the test with debug compilation: 

```
COMPILE | -DAPP=S2S  -DDEBUG=ON -DCCPP_SUITES=FV3_GFS_v16_coupled,FV3_GFS_v16_coupled_nsstNoahmpUGWPv1                                       | - wcoss_cray                            | fv3 |

RUN     | cpld_control_c384_p7                                                                                                    | - wcoss_cray                            | fv3 |

```

**Comment by junwang-noaa** [comment] 2021-09-17 03:08
@JessicaMeixner-NOAA Thanks for the update. I will close the issue then.

**Closed as completed by junwang-noaa** 2021-09-17 03:08 UTC
Labels: bug
