### ISSUE TITLE
Issue on the baselines with long_name and units: control_p8_atmlnd_sbs, datm_cdeps_lnd_gswp3

### ISSUE THREAD

**Issue by jkbk2004** [ufs-community/ufs-weather-model#1478] opened 2022-10-28 13:40 UTC
The attributes flipped on those baselines introduced from PR #1443: develop-20221026.

**Comment by DeniseWorthen** [comment] 2024-02-06 15:53
@uturuncoglu I just checked the latest baseline for the ``control_p8_atmlnd_sbs_intel`` and I no longer see the issue reported by @DusanJovic-NOAA here https://github.com/ufs-community/ufs-weather-model/issues/1443#issuecomment-1294979287

I see 

```
ncdump -c ufs.cpld.lnd.out.2021-03-22-64800.tile3.nc|grep ps
	double ps(time, grid_yt, grid_xt) ;
		ps:long_name = "surface pressure" ;
		ps:missing_value = 1.e+20 ;
		ps:units = "Pa" ;
```

Was this the only field that had the attributes incorrect? It appears it was fixed at some point? Can we close this issue?

**Comment by uturuncoglu** [comment] 2024-02-06 16:15
@DeniseWorthen Yes. As a part of restructuring I/O layer (FMS -> ESMF Multi-tile I/O), we fixed this issue. So we could close this. 

As I know we have another issue in the land output like type mismatch for integer variables and their missing_values. I think that the issue is in the ESMF I/O layer and the way of defining attributes but I could not go further to find the source.  For example, the following variable is defined as int but when you add missing_value it adds as short.

```
	int soiltyp(time, grid_yt, grid_xt) ;
		soiltyp:long_name = "soil type" ;
		soiltyp:missing_value = -999s ;
		soiltyp:units = "1" ;
```

This is just a very minor issue that will appear when you try to read those integer variables through the NCL and it complains (just warning) about type mismatch between variable and missing value and can be suppressed with following additional code,

```
  ;--- turn off missing value check ---
  setfileoption("nc", "MissingToFillValue", False)
```

**Comment by DeniseWorthen** [comment] 2024-02-06 17:58
@uturuncoglu Thanks. I'll go ahead and close this. I thoughtI remembered Dusan finding a similar issue about attribute type mis-match and I thought it was in ESMF. I'll see if I can track that down.

**Closed as completed by DeniseWorthen** 2024-02-06 17:58 UTC

**Comment by DeniseWorthen** [comment] 2024-02-06 18:07
This is the issue I remember....not sure it is related though. https://github.com/NOAA-EMC/fv3atm/pull/618

**Comment by uturuncoglu** [comment] 2024-02-06 18:11
@DeniseWorthen Thanks for the pointer. Let me check. Maybe same also applies to my issue.
