### ISSUE TITLE
FV3 seg fault when writing restart files when using GSD physics with HRRR ICs (nine soil levels)

### ISSUE THREAD

**Issue by JeffBeck-NOAA** [ufs-community/ufs-weather-model#19] opened 2019-12-18 18:45 UTC
From Gerard Ketefian:

Using HRRR ICs, processed through chgres to run the SAR with GSD physics, and can successfully produce write-component output (dynf*.nc and phyf*.nc files).  However, once the FV3 executable gets to restart file I/O, it fails with a segmentation fault.

My log file for a sample 6-hr run is here:
/scratch2/BMC/det/beck/SAR-FV3/run_dirs/real_time2/log/run_FV3_2019100400.log

My run directory is here:
/scratch2/BMC/det/beck/SAR-FV3/run_dirs/real_time2/2019100400

And the code I'm using (gmtb/develop branch) is here:
/scratch2/BMC/det/beck/SAR-FV3/regional_workflow/sorc/NEMSfv3gfs

Here's the last commit that was made when I cloned the repo:
commit e30fc6c67c3c98ceab5b0859fe47780de0859b91
Merge: e769178 3042e60
Author: Dom Heinzeller <dom.heinzeller@icloud.com>
Date:   Tue Sep 24 10:53:31 2019 -0600

    Merge pull request #255 from climbfuji/cleanup_remove_thompson_satadj
   
    gmt

**Comment by jwolff-ncar** [comment] 2019-12-23 17:22
Updated information shared with @SamuelTrahanNOAA 
After consultation with Curtis, we are contacting you to see if you can take a look at an on-going fatal FV3 error that we're encountering when running the SAR-FV3 with HRRR ICs and GSD physics through CCPP.  

A summary of the problem is below:

* When using HRRR ICs (containing 9 soil levels) and either the FV3_GSD_v0 or FV3_GSD_SAR suite definition files, the model crashes when writing out restart files in the RESTART directory, specifically while writing the sfc_data.nc file.
* The traceback shows that the crash happens in one of the FMS subroutines while writing dimensions to the sfc_data.nc file.  We're pretty sure the problem is not with that FMS subroutine but with the data it is getting passed.
* We tried debugging by putting in print statements in the FMS subroutine to see exactly what it's trying to write out.  We suspect that the number of soil levels is set incorrectly somewhere (should be 9 but is set to 4).  So either certain arrays that incorrectly have 4 elements are being accessed at index 5, 6, etc., or the arrays have 9 elements, but those last 5 are filled with garbage values.
* When we initialize using GFS data, which only has 4 soil levels, but use GSD physics, the model runs to completion and the restart files are generated correctly.
* We were hoping that recent model upgrades had resolved the problem, but it still exists.

We have run a coarse 25-km resolution HRRR-like domain (for easier debugging) that contains the error, which can be found here on Hera:

/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/expt_dirs/regional_004_Sam

The log file that contains the error when running the model code is here:

/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/expt_dirs/regional_004_Sam/log/run_fcst_2019052000.log

The forecast model code for FV3 (containing CCPP as well) is here:

/scratch2/BMC/det/Gerard.Ketefian/UFS_CAM/test_gsketefian_fork_20191211_Sam/sorc/ufs_weather_model

Thanks much in advance for taking a look at this, and hopefully you'll be able to narrow it down without much of a problem.  We will need to determine whether we need to contact the CCPP team to implement a change to how the RESTART files are written out when using different suite files, or whether this should be handled by the model code itself.

**Comment by SamuelTrahanNOAA** [comment] 2019-12-23 17:31
I have a rather large number of things to work on right now, so I can't promise I'll get to this any time soon.

**Comment by climbfuji** [comment] 2019-12-23 17:37
I will be working this week Thursday and Friday, and I would have some time. But I don't want to steal it from @SamuelTrahanNOAA or even worse duplicate efforts. Sam, what do you think?

**Comment by SamuelTrahanNOAA** [comment] 2019-12-23 17:40
I have other deadlines this month, so I'm certainly not working on it this week.

**Comment by climbfuji** [comment] 2019-12-23 17:41
Ok. I'll take a look at it this week. Thanks!

**Comment by jwolff-ncar** [comment] 2019-12-23 17:44
That's great - thanks for the offer to look at it @climbfuji

**Comment by JeffBeck-NOAA** [comment] 2019-12-23 17:45
Thanks much, Dom!

**Comment by climbfuji** [comment] 2019-12-23 18:00
@JeffBeck-NOAA @gsketefian I have no idea about your workflow, so I will need to ask you for a number of things (probably as I move along ...)

(1) what is the `compile.sh` command you used?

**Comment by JeffBeck-NOAA** [comment] 2019-12-23 18:07
No worries!  Here's the compile.sh command that I used most recently (and
this executable is running the real time run at the moment).  This is the
static build of FV3_GSD_SAR.  Previously I had built CCPP dynamically, but
both result in the same problem.

./compile.sh
/scratch2/BMC/det/beck/SAR-FV3/regional_workflow/sorc/ufs_weather_model/FV3
hera.intel 'CCPP=Y STATIC=Y 32BIT=Y REPRO=N SUITES=FV3_GSD_SAR'

- Jeff

**Comment by climbfuji** [comment] 2019-12-23 18:07
> No worries! Here's the compile.sh command that I used most recently (and this executable is running the real time run at the moment). This is the static build of FV3_GSD_SAR. Previously I had built CCPP dynamically, but both result in the same problem. ./compile.sh /scratch2/BMC/det/beck/SAR-FV3/regional_workflow/sorc/ufs_weather_model/FV3 hera.intel 'CCPP=Y STATIC=Y 32BIT=Y REPRO=N SUITES=FV3_GSD_SAR' - Jeff
> […](#)

Thanks!

**Comment by climbfuji** [comment] 2019-12-23 18:54
This might have been just be for testing, but did you notice that you are using a blocksize of 2 in your input.nml? That doesn't make sense. Please use 32 as default on hera or any other HPC platform. For debugging purposes, use a larger value so that the number of blocks per MPI task is a small integer (e.g. 4). For example: with 200*110 columns on one tile and four MPI tasks, you have 5500 columns per MPI task. Using a block size of 1100 gives you 5 blocks, something digestable when printing debug output. But for real-time applications, please use 32.

**Comment by JeffBeck-NOAA** [comment] 2019-12-23 19:04
Dom,

I'm guessing you're looking at the 25-km HRRR test that I ran?  We have
blocksize set to 2 since it is such a coarse domain.  We use blocksize = 34
in our 3-km runs.  However, I can definitely change the default for the
coarser pre-defined domains in the community workflow.

- Jeff

- Jeff

**Comment by climbfuji** [comment] 2019-12-23 20:28
@JeffBeck-NOAA @gsketefian do you have a way to distinguish in the code where the initial conditions/boundary conditions are coming from (GFS or HRRR)?

**Comment by climbfuji** [comment] 2019-12-23 21:02
@JeffBeck-NOAA @jwolff-ncar @gsketefian @SamuelTrahanNOAA I found the issue and fixed it. You are using the latest dtc/develop, correct? If so, I will create the PR that fixes the problem there. I am wondering if we should add a regression test for the 25km domain in DEBUG mode to the ufs-weather-model regtests.

**Comment by JeffBeck-NOAA** [comment] 2019-12-23 21:47
Dom,

Wow, that was fast! BTW, we do have a way to distinguish in the code where
the IC/BCs are coming from.  It's in the var_defns.sh file as
EXTRN_MDL_NAME_ICS="HRRRX" and EXTRN_MDL_NAME_LBCS="RAPX".  You probably
don't need that anymore, but it's in the real_time2 run directory.

Yes, we are using the dtc/develop branch.  I would also definitely agree
that we should have a 25-km regression test with this setup added to
ufs-weather-model.

Thanks for your help fixing this!

- Jeff

**Comment by JeffBeck-NOAA** [comment] 2019-12-23 21:56
Also, could you explain what/where the problem was and how you fixed it?

Thanks!

**Comment by climbfuji** [comment] 2019-12-23 22:13
I compiled the code in DEBUG mode, and when I ran it it crashed in FV3/io/FV3GFS_io.F90 with an out-of-bounds write in the sfcprop_restart_write subroutine. The issue was that the deallocation and reallocation of the surface restart fields was only testing for differences between the number of soil levels in the allocated fields (4 when coldstarting from GFS, 9 from HRRR) and the number of soil levels in the arrays to write to disk (9 for RUC LSM). See here: https://github.com/NCAR/fv3atm/pull/22

**Comment by climbfuji** [comment] 2019-12-23 23:19
@JeffBeck-NOAA @gsketefian for your information

**Comment by climbfuji** [comment] 2019-12-26 15:00
Fixed by https://github.com/NCAR/fv3atm/pull/22.

**Comment by climbfuji** [comment] 2019-12-26 15:05
@JeffBeck-NOAA please close this issue.

**Closed as completed** 2019-12-26 21:55 UTC
Labels: bug

**Comment by JeffBeck-NOAA** [comment] 2019-12-27 05:22
Dom,

I've now closed this issue.  Thank you for your help with this problem and
for getting it committed to the repo so quickly!  I successfully compiled
the new code and can confirm that it's working in the real-time runs.

Thanks again!

- Jeff
