### ISSUE TITLE
The latest AQM workflow got strange O3 and PM2.5 predictions

### ISSUE THREAD

**Issue by BrianCurtis-NOAA** [ufs-community/ufs-weather-model#1581] opened 2023-01-25 15:15 UTC
## Description

AQM with the latest workflow was tested and shows very strange behavior for both O3 nd PM2.5 predictions.  It seems that the model may not be able to read emissions correctly ?

Tracking along with NOAA-EMC/AQM/issues/56

  - #1583

## Output

![plot_grp1 timeseries OZONE 2022-07-01_12 2022-07-18_12 all CONUS](https://user-images.githubusercontent.com/54634403/214048453-aa3a0cd5-e55f-4a26-a858-91b69aba89a6.png)
![plot_grp1 timeseries PM2 5 2022-07-01_12 2022-07-18_12 all CONUS](https://user-images.githubusercontent.com/54634403/214048474-1e222640-2551-4e2d-adb8-be307bf29722.png)

**Comment by junwang-noaa** [comment] 2023-01-26 18:06
Pull request https://github.com/ufs-community/ufs-weather-model/pull/1583

**Comment by junwang-noaa** [comment] 2023-03-09 14:03
PR#1583 was merged, the issue is closed.

**Closed as completed by junwang-noaa** 2023-03-09 14:03 UTC
Labels: bug
