### ISSUE TITLE
more flexible RT system

### ISSUE THREAD

**Issue by uturuncoglu** [ufs-community/ufs-weather-model#656] opened 2021-06-22 06:04 UTC
## Description
I am opening this issue because it think this topic needs more broad discussion. I know there are lots of ongoing efforts to simplify the UFS modeling infrastructure but since the model involving too fast and the RT tests are the main component of the existing infrastructure to keep continue to the development of the modeling system without breaking existing applications, the current RT system also needs to be revisited and simplified for the easy to use for the community.

The design of the current version of UFS RT system seems not flexible enough to handle multiple applications and various configurations of them in an efficient way. The design seems very FV3 and S2S centric and assumes that all the model configurations require same set of namelist files such as `input.nml`, `diag_table` etc., which is not the case for some configurations under HAFS application (i.e. DATM+HYCOM). This requires putting application specific customizations to the RT system especially to `run_tests.sh` script to support existing tests and creating clean run directories. 

The UFS is evolving so fast by including new model configurations and components (CDEPS is just one of them) to support various application and this requires more flexible, simple and clean RT system. Adding new tests to existing ones require touching multiple files under test directory and lots of testing. Currently, if user/developer wants to create a new RT for specific needs or application, the multiple files need to be changed/created,

- define test under `tests/tests` directory
- add scripts to copy input files to run directory (defined under `fv3_conf/` directory which is very FV3 centric)
- add required namelist files to `parm/` directory. 
- setup default parameters under `default_vars.sh`
  
In this approach, it is hard to keep the files consistent for specific RT and also maintain the integrity of the overall RT system. If the target is the community contribution, then this needs to be more simple and understandable. In my opinion, having multiple files to define a single RT makes it more difficult to understand and create.

## Solution
I think that having a simple central database (it could be a simple text file) that can store information about the RTs such as 
namelist files that are required for the components/configuration, location of input files/baselines, components that are activated etc. Then, the RT system could reference this database to create the run directory for particular experiment with minimal (preferable no) application specific customizations. BTW, all information required to create RT can be defined in a single file. This could also allow have more fine tune control (i.e. component level - for example only MOM6 and FV3 could require diag_table) in the rt.sh level and its subcomponents to make it more generic. In addition, there are multiple files for same namelist file such as `input.nml`, `model_configure`, `nems.configure` etc. serves as a template. This can be also simplified by using more generic templates and a new parser system that could do more than just replacing strings in the namelist files. The specific section of the namelist file can be created based on the activated component and referencing database.

**Comment by arunchawla-NOAA** [comment] 2021-06-23 00:05
Ufuk do you have a prototype in mind? How would this look like for an FV3 based and a CDEPS+MOM6 based regression test? The current system supports both options right now, but perhaps your approach would be more elegant.

**Comment by WalterKolczynski-NOAA** [comment] 2021-06-23 02:19
Ideally, this should be built on top of the same system chosen for the unified workflow, whether that be CROW or EWOK so both the model and the workflow are using a common set of tools.

**Comment by junwang-noaa** [comment] 2021-06-23 03:06
It's good to know more about CROW or EWOK, I am curious if they are simple
and flexible systems for model regression tests. What are the steps if we
want to add a new application test in the current CROW/EWOK system?

**Comment by WalterKolczynski-NOAA** [comment] 2021-06-23 03:31
Definitely flexible. Simplicity depends on your point of view. I can't speak for EWOK, but I think once set up a CROW system would be straightforward to maintain. All the configuration is done via YAML files. I also think that with a small amount of thought, we can create a layout (CROW-speak for the job flow) that would accept new tests without having to modify the layout to add "new" tasks. It would no doubt be a fair amount of work to get stood up initially, but you can probably "borrow" a fair amount from global-workflow, and I'm becoming more familiar with the system all the time so I'd be able to help.

But, it's not even decided whether workflow is going to go with CROW or EWOK, so I'd want to hold off until that gets decided. Wouldn't make much sense to do work for one and then have workflow go in the other direction.

**Comment by uturuncoglu** [comment] 2021-06-23 04:31
@arunchawla-NOAA I don't have any prototype in my mind but i worked little bit under HAFS to create fully coupled and CDEPS related RTs and based on my limited experience the current system has limitations in flexibility as well as it is hard to maintain. I agree with @WalterKolczynski-NOAA about defining configuration in a single place like YAML etc. That will definitely simplify the maintenance of the RTs and also adding new ones. I would also imagine that the new RT system need to allow used to create nemelist using more flexible templates. For example, the model_configure for the regional application has extra information abut the regional domain etc. and I am pretty sure that other namelist files has same kind of structure that depends on the underlying model configuration. The RT system needs to be smart to add only required sections to the given namelist file. This makes the number of templates that is used by the system minimal and same tamplates can be shared across different applications and configurations. Also, I am not sure it is already supported or not but I envisioned that RT needs to allow to use existing executable for the testing. In the current workflow, if the newly designed RT fails in the run (I assumed that it builds the model without issue), you need to go to configuration files and fix them and test it again. The new test builds the RT again and this is very time consuming if you have a fully coupled configuration. I think that build and run and checking phases needs to be decouple in the new RT system. By this way, user could only focus specific task in the RT (build, run, check, post-processing?) to fix it and this makes adding new RTs quick and more efficient way.

**Comment by junwang-noaa** [comment] 2021-06-23 12:41
A user interface with a yaml file may be simple from user's view,, but the underlying system to support such yaml file interface may not be as simple and easy to maintain, or flexible for operational run where efficiency may be a more important factor in my opinion. As Ufuk listed, four steps are needed to add a complete new application under the current RT system. The developer needs to provide a namelist, model configuration files, namelist (or know how to use available template to create those namelist file) and script to set up a canned case, currently the RT script does not allow users to just put in a basic information such as  experiment date, test domain in a yaml file and then to figure out a correct namelist or model configuration for the user. I am not clear about the difficulty of what Ufuk is doing for setting up HAFS regression test in RT. But current RT does allow developers to use the RT test case for debugging by using the same executable or a new executable  without rerunning the RT.  I'd like to learn more about the steps to set up such a new application with a yaml interface  file under workflow.

**Comment by uturuncoglu** [comment] 2021-06-23 16:38
@junwang-noaa i have already add new RTs for both fully coupled and also data component configurations (datm and docn) and you could see them in the following link,

https://github.com/hafs-community/ufs-weather-model/tree/feature/hafs_couplehycom_cdeps

the main issue that I had to do modification in `run_tests.sh` and also `default_vars.sh`, which makes them hard to maintain. I know that the RT requires some information from the user such as model configuration etc. but this can be defined in a more simple way and using a single location. The user does not need to make modification in `run_tests.sh` especially when new application like HAFS is defined. It is fine for experienced developers but not easy for regular user that you are waiting contribution from them.

**Comment by junwang-noaa** [comment] 2021-06-23 17:39
@uturuncoglu Thanks for letting us know the issues you have. As you may already know, the tests/tests/test_file is the text file for a user to define namelist, model configure files, and run script to set up a canned case (we may consider a yaml file if it is more user-friendly.) for a new test case. We actually don't expect developers to touch run_tests.sh unless a new application is added. For a new application, the person who adds the new application tests with the new model component needs to have decent knowledge about the test system so that he/she can add the new application test and not break current system. The updated script can be used for future tests for that application. 

Since the current system does not have the knowledge on which pieces of code to be added for the new application, I am not sure if we can expect RT system to figure out the namelist, model configure, or create configuration template as you mentioned in the issue. I'd suggest to work with RT code managers to add the new application test. From that point of view, I think there is difference from general developers who want to make contribution to improve the model or fix a bug in current configuration and  developers who want to add a completely new application. Personally I don't think it's good to ask RT script to figure out what needs to be added and where should be updated for a new application. I think there is a long way to go if we expect the RT or workflow to have capability of adding new application test automatically and run those tests on operational platforms. But for general developers, I believe the current RT allows them to add new tests based on existing test, we are trying to make the process easier and simpler. We are very happy to work with developers who are working on adding new applications, just create a issue, so the code managers will be aware and can start to help.

**Comment by arunchawla-NOAA** [comment] 2022-03-04 19:32
@uturuncoglu does this still remain an issue ? should this be changed to discussion ? or be closed ?

**Comment by uturuncoglu** [comment] 2022-03-04 19:50
@arunchawla-NOAA I think that this is still issue and need to be addressed in the future to have more clean and flexible RT system. I think it requires more broad discussion about the RT system. So, it might be good idea to change it to discussion.

**Comment by arunchawla-NOAA** [comment] 2022-03-04 20:26
@uturuncoglu there is a discussion topic on this 

https://github.com/ufs-community/ufs-weather-model/discussions/666

but not much there. I am closing this issue here, but you may want to bring some points from here to there

**Closed as completed by arunchawla-NOAA** 2022-03-04 20:26 UTC
Labels: enhancement
