### ISSUE TITLE
Which are the correct Thompson MP files to link? 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [ufs-community/ufs-weather-model#1670] opened 2023-03-21 20:00 UTC
## Description
In 
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/fv3_conf/control_run.IN#L137-L143
```
if [ $IMP_PHYSICS = 8 ]; then
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qsV2.dat .
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qgV2.dat .
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/freezeH2O.dat .
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/CCN_ACTIVATE.BIN .
fi
```
but in 
https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/fv3_conf/cpld_control_run.IN#L169-L174
```
if [ $IMP_PHYSICS = 8 ]; then
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/CCN_ACTIVATE.BIN CCN_ACTIVATE.BIN
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/freezeH2O.dat freezeH2O.dat
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qg.dat qr_acr_qg.dat
  cp    @[INPUTDATA_ROOT]/FV3_input_data_gsd/qr_acr_qs.dat qr_acr_qs.dat
fi
```
these are named more consistently with the workflow, and there have been reports of slow initialization and possibly is linked to this (See: https://github.com/NOAA-EMC/global-workflow/issues/1411) 

On some level this is a question of which are the correct Thompson MP input files that should be used? And should there be consistency between standalone and coupled runs?

**Comment by pjpegion** [comment] 2023-03-21 20:04
from 
https://github.com/ufs-community/ccpp-physics/blob/630d37494a9e32690131b0af0ea367886581ecba/physics/module_mp_thompson.F90#L378

      character(len=*), parameter :: qr_acr_qg_file = 'qr_acr_qgV2.dat'
      character(len=*), parameter :: qr_acr_qs_file = 'qr_acr_qsV2.dat'

**Comment by JessicaMeixner-NOAA** [comment] 2023-03-21 20:06
Thanks @pjpegion ! (And thanks for helping point to the original idea to help @guillaumevernieres )

**Comment by JongilHan66** [comment] 2023-03-21 20:12
@RuiyuSun Ruiyu, could you help Jessica for those ThompsonMP related questions?

**Comment by yangfanglin** [comment] 2023-03-22 03:22
Under /scratch1/NCEPDEV/global/glopara/fix/am/20220805 both versions exist.   It appears the *V2 is a later version.  These files are used by the non-aerosol-aware version of the Thompson microphysics scheme.

-rw-r--r-- 1 role.glopara global 51518256 Oct  1  2019 qr_acr_qg.dat
-rw-r--r-- 1 role.glopara global 33118944 Oct  1  2019 qr_acr_qs.dat
-rw-r--r-- 1 role.glopara global 68077680 Mar 30  2021 qr_acr_qgV2.dat
-rw-r--r-- 1 role.glopara global 33118944 Mar 30  2021 qr_acr_qsV2.dat

Checking the history of the file physics/module_mp_thompson.F90 shows that Greg changed to V2 in this commit :  "update Thompson more similar to WRF-v4.3 "  https://github.com/ufs-community/ccpp-physics/commit/d8f4ffbfbe519ee627c6144505d029c4720bd9f3  back in February  13, 2021.    

The code was written in such as way that if qr_acr_qg_file/qr_acr_qs_file (defined as qr_acr_qgV2.dat/qr_acr_qsV2.dat in the updated code) are not found and force_read_thompson=F (by default) then  the program will compute and recreate these two tables at initialization time.

  I checked the forecast log file and did find 

  0:    creating rain collecting graupel table
  0:  ThompMP: computing qr_acr_qg
  0:  Writing qr_acr_qgV2.dat in Thompson MP init
  0: Computing rain collecting graupel table took    189.221 seconds.
  0:    creating rain collecting snow table
  0:  ThompMP: computing qr_acr_qs
  0:  Writing qr_acr_qsV2.dat in Thompson MP init
  0: Computing rain collecting snow table took     34.670 seconds.

So since Feb 2021 the UFS global models have been precomputing these two tables at initialization time.   I compared qr_acr_qgV2.dat, which is remade in a C384 run, with that in the "fix" directory.  They are indeed different.

Now the question is:  should we let the model recompute every time at initialization, or update the workflow script to use the V2 version of the files ?    We need to assess the impact before we update the workflow script to use the precomputed qr_acr_qgV2.dat and qr_acr_qsV2.dat saved under the /scratch1/NCEPDEV/global/glopara/fix/am/20220805

Note that since RRFS is using the aerosol-aware version of the Thompson MP.    RRFS is not affected.

**Comment by JessicaMeixner-NOAA** [comment] 2023-03-22 12:22
Are these fields supposed to be resolution dependent and therefore  have a fix file for each of the model resolutions for these if we do not compute these every time?   We might want some option to use these fix files at least in engineering tests because I've heard that this is taking a significant part of the total computational time for the lower-resolution engineering tests.    Also, it seems like simply checking if it's Thompson MP is not a sufficient check, that we should also know if it's aerosol-aware or not, again assuming that we keep using these files and not re-compute them every time.

**Comment by junwang-noaa** [comment] 2023-03-22 12:34
```I've heard that this is taking a significant part of the total computational time for the lower-resolution engineering tests.```
@JessicaMeixner-NOAA Could you elaborate more on what the lower-resolution engineering tests are?

**Comment by yangfanglin** [comment] 2023-03-22 12:48
It is not resolution dependent.  Yes, it takes a significant amount of time to initialize.  We should plan for using the precomputed ones.  Let's wait for Greg and Ruiyu to weigh in, and run some tests, before we make a decision.  For RT and other development that science is less of a concern, you can switch to use qr_acr_qgV2.dat and qr_acr_qsV2.dat to reduce model initialization time.

**Comment by RuiyuSun** [comment] 2023-03-22 13:09
The tables are not resolution dependent. They should be used to save the computing time.

**Comment by JessicaMeixner-NOAA** [comment] 2023-03-22 13:10
> `I've heard that this is taking a significant part of the total computational time for the lower-resolution engineering tests.` @JessicaMeixner-NOAA Could you elaborate more on what the lower-resolution engineering tests are?

@guillaumevernieres will have to fill in those details

**Comment by junwang-noaa** [comment] 2023-03-22 13:39
Thanks for the info. @guillaumevernieres I assume the the lower-resolution engineering tests are not from the ufs-weather-model RT tests, please clarify.

Currently all the RT tests, coupled or standalone,  are using qr_acr_qgV2.dat and qr_acr_qsV2.dat. This is consistent with the model code @pjpegion pointed to. In other words, the two file names are now hardcoded in the ccpp/physics/module_mp_thompson.F90. There is no message of "0: ThompMP: computing qr_acr_qg" in any of RT tests at this time as @yangfanglin saw in his run, assuming from global workflow.

Back to @JessicaMeixner-NOAA  question, currently both qr_acr_qg.dat/qr_acr_qs.dat  and qr_acr_qgV2.dat/qr_acr_qsV2.dat are copied to the cpld test run directories. The  qr_acr_qg.dat/qr_acr_qs.dat are copied through the cpld_control_run.IN as you listed, while qr_acr_qgV2.dat/qr_acr_qsV2.dat are copied through:

https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/run_test.sh#L182

So the RT test cases run as expected, there is no additional computation for the qr_acr_qg.dat. We will update the cpld_control_run.IN to clean up the old qr_acr_qg.dat/qr_acr_qs.dat to avoid confusion. Please let us know there is still any issue with the RT test settings. 

@aerorahul FYI.

**Comment by guillaumevernieres** [comment] 2023-03-22 15:01
That's correct @junwang-noaa , I was referring to the testing of the cycling applications in the global-workflow, not the RT.

**Comment by junwang-noaa** [comment] 2023-03-22 19:45
I created a ufs-weather-model branch thompsonfiles with following changes:
1) qr_acr_qgV2.dat/qr_acr_qsV2.dat are now copied from /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/FV3_fix, they are same as /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/input-data-20221101/FV3_input_data_gsd/.
2) the cpld_control_run.IN will copy  qr_acr_qgV2.dat/qr_acr_qsV2.dat to run directory, instead of  qr_acr_qg.dat/qr_acr_qs.dat to avoid confusion.
The changes can be seen at: 
https://github.com/ufs-community/ufs-weather-model/compare/develop...junwang-noaa:thompsonfiles?expand=1

There is no results change from the changes above. I ran full RT on hera and it passed. 
/scratch1/NCEPDEV/nems/Jun.Wang/nems/vlab/20230306/ufs-weather-model/tests/RegressionTests_hera.intel.log

@yangfanglin The changes here are for clean up. Please let me know if different physics settings are required for Thompson MP.

**Comment by junwang-noaa** [comment] 2023-03-23 13:59
I will make a pull PR to Dusan's PR #1633  so that we can get it committed. Again, there is no result change from the code changes. 

Also. the qr_acr_qgV2.dat/qr_acr_qsV2.dat used in UFS WM are the same as the files under /scratch1/NCEPDEV/global/glopara/fix/am/20220805

**Comment by gthompsnWRF** [comment] 2023-03-23 19:52
The look-up tables for Thompson microphysics are not resolution dependent.  The two in question are the most costly collection equations in which rain collides with either snow or graupel. A "bin model" representation is made from the assumed particle size distribution to get as exact a calculation as we can based on size-dependent collision efficiencies as we know from the literature.  Schemes like GFDL microphysics use a constant collection efficiency based on old papers that have serious problems with particles with nearly the same fall speed (like drizzle and snow that can both fall close to 1 m/s) and give far too much collection (in GFDL).  I began using version numbers with tables when I wanted to alter my range of values of graupel intercept parameter along with a newer diagnostic to compute intercept parameter.  Each time any part of the assumed PSD is changed, a new table must be calculated so any future changes to any of rain, snow, or graupel distribution assumptions (or mass relationships) must make new tables and increment its number to be consistent.

**Comment by yangfanglin** [comment] 2023-03-23 23:27
@gthompsnWRF Greg, thank you for explaining why newer tables were created.  @aerorahul  Rahul, please go ahead to update the workflow to point to qr_acr_qgV2.dat/qr_acr_qsV2.dat.    @RuiyuSun Ruiyu is running a test for sanity checks.  I'd expect the impact on model overall performance is small.   We will dive deeper if Ruyu's test show any alarming differences from the control.

**Comment by aerorahul** [comment] 2023-03-24 14:31
A PR in the global-workflow has been opened to use the pre-computed tables.
See https://github.com/NOAA-EMC/global-workflow/pull/1422

**Comment by junwang-noaa** [comment] 2023-03-28 18:15
The clean up code is committed in PR#1633. The issue will be committed

**Closed as completed by junwang-noaa** 2023-03-28 18:15 UTC
Labels: bug
